// ─────────────────────────────────────────────────
// DWL Search Index — 60+ Data Stories
// All modules from the deployed site
// ─────────────────────────────────────────────────

export interface SearchEntry {
  id: string
  number: string
  title: string
  category: string
  description: string
  tags: string[] // searchable keywords
  href: string
}

export const SEARCH_INDEX: SearchEntry[] = [
  // ═══ CORE DATA MODULES (001–005) ═══
  {
    id: 'maghreb-compared',
    number: '001',
    title: 'The Maghreb Compared',
    category: 'Comparative Analysis',
    description: 'Morocco, Tunisia, and Algeria side by side. Population, GDP, tourism, investment, demographics.',
    tags: ['morocco', 'tunisia', 'algeria', 'gdp', 'population', 'comparison', 'north africa', 'maghreb', 'investment', 'development'],
    href: '/data/maghreb-compared',
  },
  {
    id: 'morocco-population',
    number: '002',
    title: 'Morocco Population Density',
    category: 'Interactive Map',
    description: 'Mapbox heatmap of Morocco\'s 12 administrative regions. Population, density, urbanization rate.',
    tags: ['population', 'density', 'regions', 'urbanization', 'mapbox', 'casablanca', 'marrakech', 'map', 'demographics'],
    href: '/data/morocco-population',
  },
  {
    id: 'al-andalus',
    number: '003',
    title: 'The Al-Andalus Corridor',
    category: 'Cultural Geography',
    description: 'One continuous cultural bridge from Seville to Fes. Architecture, music, food, language — four layers of shared DNA.',
    tags: ['al-andalus', 'spain', 'seville', 'fes', 'architecture', 'music', 'food', 'language', 'flamenco', 'moorish', 'alhambra', 'córdoba'],
    href: '/data/al-andalus',
  },
  {
    id: 'morocco-economy',
    number: '004',
    title: 'Morocco Economy in One Page',
    category: 'Economic Intelligence',
    description: 'GDP, exports, FDI, tourism, remittances, key sectors. The essential economic snapshot.',
    tags: ['gdp', 'economy', 'exports', 'fdi', 'tourism revenue', 'remittances', 'phosphate', 'automotive', 'world bank', 'imf'],
    href: '/data/morocco-economy',
  },
  {
    id: 'morocco-agriculture',
    number: '005',
    title: 'What Morocco Grows & Sends to the World',
    category: 'Illustrated Data',
    description: 'Radial harvest wheel. Tomatoes, berries, citrus, olives, argan, seafood — ranked by export value.',
    tags: ['agriculture', 'exports', 'tomatoes', 'berries', 'citrus', 'olives', 'argan', 'seafood', 'farming', 'souss', 'harvest'],
    href: '/data/morocco-agriculture',
  },

  // ═══ EXPANDED MODULES (006–020) ═══
  {
    id: 'water-crisis',
    number: '006',
    title: 'Morocco\'s Water Crisis',
    category: 'Environmental Data',
    description: 'Reservoir levels, rainfall decline, desalination projects. The data behind Morocco\'s drought emergency.',
    tags: ['water', 'drought', 'reservoir', 'desalination', 'rainfall', 'agriculture', 'climate', 'dam', 'crisis'],
    href: '/data/water-crisis',
  },
  {
    id: 'dynasty-timeline',
    number: '007',
    title: 'The Dynasties of Morocco',
    category: 'Historical Timeline',
    description: 'Idrisids to Alaouites. 1,200 years of Moroccan rulers, capitals, and power shifts.',
    tags: ['dynasty', 'history', 'idrisids', 'almoravids', 'almohads', 'marinids', 'saadians', 'alaouites', 'sultan', 'king', 'fes', 'marrakech'],
    href: '/data/dynasty-timeline',
  },
  {
    id: 'seasonal-produce',
    number: '008',
    title: 'Seasonal Produce Wheel',
    category: 'Food Intelligence',
    description: 'What\'s in season in Morocco month by month. Static interactive wheel with 30+ crops.',
    tags: ['seasonal', 'produce', 'food', 'vegetables', 'fruit', 'market', 'souk', 'cooking', 'season'],
    href: '/data/seasonal-produce',
  },
  {
    id: 'medina-atlas',
    number: '009',
    title: 'The Medina Atlas',
    category: 'Urban Geography',
    description: 'Mapbox atlas of Morocco\'s historic medinas. Gates, fondouks, mosques, hammams, souks.',
    tags: ['medina', 'marrakech', 'fes', 'gates', 'bab', 'souk', 'fondouk', 'mosque', 'hammam', 'old city', 'urban'],
    href: '/data/medina-atlas',
  },
  {
    id: 'spice-map',
    number: '010',
    title: 'The Spice Map',
    category: 'Food Intelligence',
    description: 'Morocco\'s spice geography. Ras el hanout, cumin, saffron, paprika — origins, routes, and uses.',
    tags: ['spice', 'ras el hanout', 'cumin', 'saffron', 'paprika', 'food', 'cooking', 'souk', 'market'],
    href: '/data/spice-map',
  },
  {
    id: 'amazigh-identity',
    number: '011',
    title: 'Amazigh Identity Map',
    category: 'Cultural Geography',
    description: 'Berber-speaking regions, Tifinagh script distribution, tribal territories, and language survival.',
    tags: ['amazigh', 'berber', 'tifinagh', 'language', 'tribal', 'atlas', 'rif', 'souss', 'tuareg', 'indigenous'],
    href: '/data/amazigh-identity',
  },
  {
    id: 'phosphate-kingdom',
    number: '012',
    title: 'The Phosphate Kingdom',
    category: 'Resource Intelligence',
    description: 'Morocco holds 75% of world phosphate reserves. OCP Group, Khouribga mines, global fertilizer flows.',
    tags: ['phosphate', 'ocp', 'mining', 'khouribga', 'fertilizer', 'exports', 'resources', 'geology'],
    href: '/data/phosphate-kingdom',
  },
  {
    id: 'moroccan-diaspora',
    number: '013',
    title: 'The Moroccan Diaspora',
    category: 'Demographics',
    description: 'Where Moroccans live abroad. France, Spain, Italy, Netherlands, Belgium, Canada — remittance flows.',
    tags: ['diaspora', 'migration', 'remittances', 'france', 'spain', 'europe', 'mre', 'expatriate'],
    href: '/data/moroccan-diaspora',
  },
  {
    id: 'world-cup-2030',
    number: '014',
    title: '2030 World Cup Infrastructure',
    category: 'Event Intelligence',
    description: 'Stadium builds, transport upgrades, hotel capacity, host city readiness for FIFA 2030.',
    tags: ['world cup', '2030', 'fifa', 'stadium', 'casablanca', 'rabat', 'marrakech', 'infrastructure', 'football'],
    href: '/data/world-cup-2030',
  },
  {
    id: 'tgv-network',
    number: '015',
    title: 'The TGV & Rail Network',
    category: 'Infrastructure',
    description: 'Al Boraq high-speed rail, conventional network, planned extensions, passenger data.',
    tags: ['tgv', 'train', 'rail', 'al boraq', 'oncf', 'transport', 'casablanca', 'tangier', 'infrastructure'],
    href: '/data/tgv-network',
  },
  {
    id: 'solar-atlas',
    number: '016',
    title: 'Morocco\'s Solar Atlas',
    category: 'Energy Intelligence',
    description: 'Noor Ouarzazate, MASEN projects, solar irradiance data. Morocco\'s renewable energy ambition.',
    tags: ['solar', 'energy', 'renewable', 'noor', 'ouarzazate', 'masen', 'electricity', 'green', 'climate'],
    href: '/data/solar-atlas',
  },
  {
    id: 'literary-map',
    number: '017',
    title: 'Literary Morocco',
    category: 'Cultural Intelligence',
    description: 'Writers who lived, wrote, or set stories in Morocco. Bowles, Burroughs, Choukri, Canetti, Mrabet.',
    tags: ['literature', 'books', 'writers', 'tangier', 'bowles', 'burroughs', 'choukri', 'beat generation', 'interzone'],
    href: '/data/literary-map',
  },
  {
    id: 'geometric-patterns',
    number: '018',
    title: 'The Geometry of Zellige',
    category: 'Craft Intelligence',
    description: 'Mathematical principles behind Moroccan tilework. Star patterns, tessellation, symmetry groups.',
    tags: ['zellige', 'tiles', 'geometry', 'patterns', 'mathematics', 'tessellation', 'craft', 'architecture', 'fes'],
    href: '/data/geometric-patterns',
  },
  {
    id: 'moroccan-ports',
    number: '019',
    title: 'Morocco\'s Port Strategy',
    category: 'Trade Intelligence',
    description: 'Tanger Med, Casablanca, Nador West Med. Container throughput, trade routes, Africa gateway.',
    tags: ['ports', 'tanger med', 'casablanca', 'trade', 'shipping', 'containers', 'africa', 'logistics'],
    href: '/data/moroccan-ports',
  },
  {
    id: 'carpet-atlas',
    number: '020',
    title: 'The Carpet Atlas',
    category: 'Craft Intelligence',
    description: 'Regional rug traditions mapped. Beni Ourain, Azilal, Boucherouite, Kilim, Hanbel — origins and motifs.',
    tags: ['carpet', 'rug', 'beni ourain', 'azilal', 'boucherouite', 'kilim', 'weaving', 'craft', 'atlas mountains'],
    href: '/data/carpet-atlas',
  },

  // ═══ MODULES 021–040 ═══
  {
    id: 'music-traditions',
    number: '021',
    title: 'Morocco\'s Musical Traditions',
    category: 'Cultural Intelligence',
    description: 'Gnawa, Andalusi, Amazigh, Chaabi, Rai. Five traditions mapped by region and lineage.',
    tags: ['music', 'gnawa', 'andalusi', 'chaabi', 'rai', 'amazigh', 'essaouira', 'fes', 'festival'],
    href: '/data/music-traditions',
  },
  {
    id: 'olive-oil',
    number: '022',
    title: 'The Olive Oil Economy',
    category: 'Agricultural Intelligence',
    description: 'Morocco\'s olive regions, production data, cooperatives, and export markets.',
    tags: ['olive', 'oil', 'agriculture', 'meknes', 'cooperatives', 'exports', 'food'],
    href: '/data/olive-oil',
  },
  {
    id: 'imperial-cities',
    number: '023',
    title: 'The Four Imperial Cities',
    category: 'Historical Geography',
    description: 'Fes, Marrakech, Meknes, Rabat. Each dynasty chose its capital. The power map of Morocco.',
    tags: ['fes', 'marrakech', 'meknes', 'rabat', 'imperial', 'capital', 'dynasty', 'history'],
    href: '/data/imperial-cities',
  },
  {
    id: 'ramadan-moon',
    number: '024',
    title: 'Ramadan Moon',
    category: 'Living Data',
    description: 'Hijri calendar, prayer times, ftour traditions, Laylat al-Qadr countdown.',
    tags: ['ramadan', 'islam', 'prayer', 'fasting', 'ftour', 'mosque', 'calendar', 'hijri', 'moon'],
    href: '/data/ramadan-moon',
  },
  {
    id: 'saharan-routes',
    number: '025',
    title: 'Trans-Saharan Trade Routes',
    category: 'Historical Geography',
    description: 'Salt, gold, slaves, manuscripts. The ancient trade networks that built Timbuktu and Marrakech.',
    tags: ['sahara', 'trade', 'gold', 'salt', 'timbuktu', 'caravan', 'desert', 'trans-saharan'],
    href: '/data/saharan-routes',
  },
  {
    id: 'argan-triangle',
    number: '026',
    title: 'The Argan Triangle',
    category: 'Environmental Intelligence',
    description: 'UNESCO biosphere reserve. The only place on earth argan trees grow. Cooperatives, cosmetics, cooking.',
    tags: ['argan', 'oil', 'souss', 'essaouira', 'cooperatives', 'women', 'unesco', 'cosmetics', 'tree'],
    href: '/data/argan-triangle',
  },
  {
    id: 'cinema-morocco',
    number: '027',
    title: 'Cinema Morocco',
    category: 'Cultural Intelligence',
    description: 'Ouarzazate studios, filmed-in-Morocco productions, Game of Thrones locations, Atlas Corporation.',
    tags: ['cinema', 'film', 'ouarzazate', 'gladiator', 'game of thrones', 'hollywood', 'studio', 'atlas'],
    href: '/data/cinema-morocco',
  },
  {
    id: 'tea-ceremony',
    number: '028',
    title: 'The Anatomy of Moroccan Tea',
    category: 'Food Intelligence',
    description: 'Chinese gunpowder green tea, fresh mint, sugar. How it arrived, how it\'s made, why it matters.',
    tags: ['tea', 'mint', 'atay', 'ceremony', 'chinese', 'gunpowder', 'green tea', 'hospitality'],
    href: '/data/tea-ceremony',
  },
  {
    id: 'french-protectorate',
    number: '029',
    title: 'The French Protectorate',
    category: 'Historical Timeline',
    description: '1912–1956. Lyautey, ville nouvelle planning, resistance movements, independence.',
    tags: ['french', 'protectorate', 'colonial', 'lyautey', 'independence', 'resistance', '1956', 'ville nouvelle'],
    href: '/data/french-protectorate',
  },
  {
    id: 'hammam-culture',
    number: '030',
    title: 'Hammam Culture',
    category: 'Cultural Intelligence',
    description: 'The social architecture of the Moroccan bathhouse. Design, ritual, products, neighborhood role.',
    tags: ['hammam', 'bath', 'bathhouse', 'social', 'ritual', 'architecture', 'beldi', 'ghassoul'],
    href: '/data/hammam-culture',
  },
  {
    id: 'storks-eye-view',
    number: '031',
    title: 'A Stork\'s Eye View',
    category: 'Living Data',
    description: 'White stork migration, nesting colonies, Gibraltar flyway. Live migration status based on current month.',
    tags: ['stork', 'bird', 'migration', 'gibraltar', 'nesting', 'chellah', 'volubilis', 'wildlife'],
    href: '/data/storks-eye-view',
  },
  {
    id: 'riad-architecture',
    number: '032',
    title: 'The Anatomy of a Riad',
    category: 'Architecture',
    description: 'Courtyard, fountain, zellige, tadlekt, moucharabieh. Deconstructing the Moroccan house form.',
    tags: ['riad', 'architecture', 'courtyard', 'zellige', 'tadlekt', 'marrakech', 'fes', 'house', 'interior'],
    href: '/data/riad-architecture',
  },
  {
    id: 'cannabis-rif',
    number: '033',
    title: 'Cannabis & the Rif',
    category: 'Agricultural Intelligence',
    description: 'The Rif Mountains produce most of Europe\'s hashish. Legalization debate, economic impact, history.',
    tags: ['cannabis', 'rif', 'hashish', 'kif', 'agriculture', 'legalization', 'chefchaouen', 'ketama'],
    href: '/data/cannabis-rif',
  },
  {
    id: 'atlantic-coast',
    number: '034',
    title: 'The Atlantic Coast',
    category: 'Coastal Geography',
    description: 'Tangier to Dakhla. 3,500 km of coastline, fishing ports, surf breaks, wind energy.',
    tags: ['coast', 'atlantic', 'essaouira', 'dakhla', 'agadir', 'fishing', 'surf', 'wind', 'beach'],
    href: '/data/atlantic-coast',
  },
  {
    id: 'date-palm-oases',
    number: '035',
    title: 'The Date Palm Oases',
    category: 'Agricultural Intelligence',
    description: 'Draa Valley, Ziz Valley, Tafilalet. Oasis ecology, palm varieties, climate threat.',
    tags: ['date', 'palm', 'oasis', 'draa', 'ziz', 'tafilalet', 'erfoud', 'zagora', 'desert', 'irrigation'],
    href: '/data/date-palm-oases',
  },
  {
    id: 'leather-tanneries',
    number: '036',
    title: 'The Tanneries',
    category: 'Craft Intelligence',
    description: 'Fes Chouara tannery. 900 years of leather production. Process, dyes, labor, tourism.',
    tags: ['tannery', 'leather', 'fes', 'chouara', 'craft', 'dyeing', 'traditional', 'labor'],
    href: '/data/leather-tanneries',
  },
  {
    id: 'jewish-heritage',
    number: '037',
    title: 'Jewish Heritage in Morocco',
    category: 'Cultural Geography',
    description: 'Mellahs, synagogues, cemeteries, the 250,000 who left, the legacy that stayed.',
    tags: ['jewish', 'mellah', 'synagogue', 'heritage', 'sephardic', 'israel', 'essaouira', 'fes', 'marrakech'],
    href: '/data/jewish-heritage',
  },
  {
    id: 'moroccan-fashion',
    number: '038',
    title: 'Moroccan Fashion Intelligence',
    category: 'Cultural Intelligence',
    description: 'Caftan, djellaba, babouche, takchita. Traditional garments, contemporary designers, industry data.',
    tags: ['fashion', 'caftan', 'djellaba', 'takchita', 'babouche', 'textile', 'design', 'wedding'],
    href: '/data/moroccan-fashion',
  },
  {
    id: 'kasbah-route',
    number: '039',
    title: 'The Route of a Thousand Kasbahs',
    category: 'Architecture',
    description: 'Aït Benhaddou to Skoura. Fortified mud-brick architecture of the Draa-Tafilalet.',
    tags: ['kasbah', 'ait benhaddou', 'ouarzazate', 'skoura', 'draa', 'mud brick', 'architecture', 'unesco'],
    href: '/data/kasbah-route',
  },
  {
    id: 'couscous-friday',
    number: '040',
    title: 'Couscous Friday',
    category: 'Food Intelligence',
    description: 'The sacred Friday meal. Regional variations, technique, social meaning, UNESCO recognition.',
    tags: ['couscous', 'friday', 'food', 'tradition', 'family', 'recipe', 'unesco', 'semolina'],
    href: '/data/couscous-friday',
  },

  // ═══ MODULES 041–058 ═══
  {
    id: 'weather-portraits',
    number: '041',
    title: 'Weather Portraits',
    category: 'Living Data',
    description: 'Live weather for 8 Moroccan cities. Open-Meteo integration, NASA satellite imagery toggle.',
    tags: ['weather', 'temperature', 'climate', 'satellite', 'nasa', 'live', 'marrakech', 'casablanca', 'rain'],
    href: '/data/weather-portraits',
  },
  {
    id: 'automotive-industry',
    number: '042',
    title: 'Morocco\'s Automotive Revolution',
    category: 'Industrial Intelligence',
    description: 'Renault Tangier, Stellantis Kenitra. How Morocco became Africa\'s #1 car producer.',
    tags: ['automotive', 'car', 'renault', 'stellantis', 'tangier', 'kenitra', 'industry', 'exports', 'manufacturing'],
    href: '/data/automotive-industry',
  },
  {
    id: 'tagine-atlas',
    number: '043',
    title: 'The Tagine Atlas',
    category: 'Food Intelligence',
    description: 'Regional tagine variations mapped. Marrakech lamb-prune, Fes chicken-olive, coastal fish tagines.',
    tags: ['tagine', 'food', 'cooking', 'recipe', 'regional', 'lamb', 'chicken', 'fish', 'marrakech', 'fes'],
    href: '/data/tagine-atlas',
  },
  {
    id: 'atlas-mountains',
    number: '044',
    title: 'The Atlas Mountains',
    category: 'Physical Geography',
    description: 'High Atlas, Middle Atlas, Anti-Atlas. Elevation profiles, Toubkal, ski stations, transhumance.',
    tags: ['atlas', 'mountains', 'toubkal', 'high atlas', 'trekking', 'ski', 'oukaimeden', 'imlil', 'berber'],
    href: '/data/atlas-mountains',
  },
  {
    id: 'bread-of-morocco',
    number: '045',
    title: 'The Bread of Morocco',
    category: 'Food Intelligence',
    description: 'Khobz, msemen, baghrir, rghaif, harcha. Daily bread variations, communal ovens, wheat dependency.',
    tags: ['bread', 'khobz', 'msemen', 'baghrir', 'rghaif', 'bakery', 'ferran', 'wheat', 'food'],
    href: '/data/bread-of-morocco',
  },
  {
    id: 'university-heritage',
    number: '046',
    title: 'The World\'s Oldest Universities',
    category: 'Educational Heritage',
    description: 'Al-Qarawiyyin (859 CE), Ibn Yusuf, Ben Msik. Morocco\'s claim to the oldest continuously operating university.',
    tags: ['university', 'qarawiyyin', 'education', 'fes', 'marrakech', 'oldest', 'madrasa', 'ibn yusuf'],
    href: '/data/university-heritage',
  },
  {
    id: 'desert-types',
    number: '047',
    title: 'Not All Desert Is Sand',
    category: 'Physical Geography',
    description: 'Erg, reg, hammada, oued. The four desert types in Morocco, and why only 20% is sand.',
    tags: ['desert', 'sahara', 'erg', 'chebbi', 'chigaga', 'hammada', 'sand', 'dunes', 'geology'],
    href: '/data/desert-types',
  },
  {
    id: 'gnawa-atlas',
    number: '048',
    title: 'The Gnawa Atlas',
    category: 'Music Intelligence',
    description: 'Spiritual music tradition. Maalem lineages, lila ceremony, guembri construction, UNESCO status.',
    tags: ['gnawa', 'music', 'maalem', 'lila', 'guembri', 'essaouira', 'spiritual', 'unesco', 'festival'],
    href: '/data/gnawa-atlas',
  },
  {
    id: 'moroccan-gardens',
    number: '049',
    title: 'The Gardens of Morocco',
    category: 'Architecture',
    description: 'Majorelle, Agdal, Menara, Jnan Sbil. Islamic garden design principles, water management.',
    tags: ['garden', 'majorelle', 'menara', 'agdal', 'ysl', 'landscape', 'water', 'marrakech', 'islamic'],
    href: '/data/moroccan-gardens',
  },
  {
    id: 'migration-routes',
    number: '050',
    title: 'Migration Routes Through Morocco',
    category: 'Demographics',
    description: 'Sub-Saharan migration, Spain crossings, transit cities, policy, human stories.',
    tags: ['migration', 'africa', 'spain', 'ceuta', 'melilla', 'refugee', 'transit', 'border'],
    href: '/data/migration-routes',
  },
  {
    id: 'pottery-traditions',
    number: '051',
    title: 'The Pottery Traditions',
    category: 'Craft Intelligence',
    description: 'Fes blue, Safi polychrome, Tamegroute green, Rif pottery. Regional ceramics mapped.',
    tags: ['pottery', 'ceramics', 'fes', 'safi', 'tamegroute', 'craft', 'blue', 'green', 'artisan'],
    href: '/data/pottery-traditions',
  },
  {
    id: 'surf-coast',
    number: '052',
    title: 'Morocco\'s Surf Coast',
    category: 'Coastal Intelligence',
    description: 'Taghazout, Imsouane, Anchor Point, Sidi Kaouki. Swell data, season guide, surf economy.',
    tags: ['surf', 'taghazout', 'imsouane', 'waves', 'coast', 'beach', 'agadir', 'essaouira', 'sport'],
    href: '/data/surf-coast',
  },
  {
    id: 'wedding-atlas',
    number: '053',
    title: 'The Moroccan Wedding',
    category: 'Cultural Intelligence',
    description: 'Multi-day ceremonies, regional variations, henna night, trousseau, music, food, cost.',
    tags: ['wedding', 'marriage', 'henna', 'ceremony', 'tradition', 'caftan', 'family', 'celebration'],
    href: '/data/wedding-atlas',
  },
  {
    id: 'souks-decoded',
    number: '054',
    title: 'The Souk Decoded',
    category: 'Urban Intelligence',
    description: 'How a Moroccan market is organized. Guilds, pricing, negotiation patterns, spatial logic.',
    tags: ['souk', 'market', 'shopping', 'marrakech', 'fes', 'negotiation', 'craft', 'guild', 'medina'],
    href: '/data/souks-decoded',
  },
  {
    id: 'before-sahara',
    number: '055',
    title: 'Before the Sahara',
    category: 'Environmental Data',
    description: 'Desertification, green belt projects, NDVI vegetation data. The land between Atlas and sand.',
    tags: ['sahara', 'desertification', 'vegetation', 'climate', 'environment', 'green belt', 'drought'],
    href: '/data/before-sahara',
  },
  {
    id: 'harvest-calendar',
    number: '056',
    title: 'The Harvest Calendar',
    category: 'Living Data',
    description: 'A living clock of Moroccan agriculture. 32 crops, auto-highlights current month, play/pause.',
    tags: ['harvest', 'agriculture', 'seasonal', 'crops', 'farming', 'calendar', 'live', 'monthly', 'produce'],
    href: '/data/harvest-calendar',
  },
  {
    id: 'bird-atlas',
    number: '057',
    title: 'The Bird Atlas',
    category: 'Wildlife Intelligence',
    description: 'North Africa\'s bird preservation areas and migration flyways. 27 IBAs, 3 flyways, 509 species.',
    tags: ['bird', 'migration', 'flyway', 'ibis', 'wildlife', 'nature', 'wetland', 'conservation', 'birdlife'],
    href: '/data/bird-atlas',
  },
  {
    id: 'islamic-spain',
    number: '058',
    title: 'Islamic Spain — 781 Years of Al-Andalus',
    category: 'Historical Timeline',
    description: 'From Tariq ibn Ziyad\'s 711 crossing to the fall of Granada. Vertical timeline and Mapbox map.',
    tags: ['al-andalus', 'spain', 'islamic', 'umayyad', 'córdoba', 'granada', 'alhambra', 'reconquista', 'history', '711', '1492', 'caliphate'],
    href: '/data/islamic-spain',
  },

  // ═══ NEW MODULES (Feb 20, 2026) ═══
  {
    id: 'surf-coast',
    number: '047',
    title: "Morocco's Surf Coast",
    category: 'Coastal Intelligence',
    description: '15 surf breaks mapped from Safi to Essaouira. Swell data, season guide, and the economics of a 50,000-guest-per-year surf boom.',
    tags: ['surf', 'taghazout', 'imsouane', 'anchor point', 'sidi kaouki', 'waves', 'ocean', 'atlantic', 'beach', 'swell'],
    href: '/data/surf-coast',
  },
  {
    id: 'wedding-atlas',
    number: '048',
    title: 'The Moroccan Wedding',
    category: 'Event Intelligence',
    description: 'Seven days, seven outfits. Henna night, hammam, amariya, negafa, the feast. Regional variations, bridal wardrobe, and cost breakdown.',
    tags: ['wedding', 'marriage', 'henna', 'negafa', 'amariya', 'caftan', 'ceremony', 'tradition', 'family', 'celebration'],
    href: '/data/wedding-atlas',
  },
  {
    id: 'before-the-sahara',
    number: '049',
    title: 'Before the Sahara',
    category: 'Environmental Intelligence',
    description: 'Desertification, NDVI vegetation data, oasis collapse, green belt projects. The land between Atlas and sand.',
    tags: ['desert', 'sahara', 'desertification', 'oasis', 'ndvi', 'vegetation', 'climate', 'drought', 'water', 'green wall'],
    href: '/data/before-the-sahara',
  },
  {
    id: 'souk-decoded',
    number: '050',
    title: 'The Souk Decoded',
    category: 'Urban Intelligence',
    description: 'How a Moroccan market is organized. Guilds, pricing logic, negotiation patterns, spatial architecture, and the economics of the medina.',
    tags: ['souk', 'market', 'medina', 'trade', 'guild', 'craft', 'negotiation', 'commerce', 'economy', 'marrakech'],
    href: '/data/souk-decoded',
  },
  {
    id: 'tagine-atlas',
    number: '051',
    title: 'The Tagine Atlas',
    category: 'Culinary Intelligence',
    description: 'Regional tagine variations mapped. Marrakech lamb-prune, Fes chicken-olive, coastal fish chermoula, Berber mountain. Spice pantry, vessel science, cultural rules.',
    tags: ['tagine', 'food', 'cooking', 'lamb', 'chicken', 'fish', 'spice', 'saffron', 'marrakech', 'fes'],
    href: '/data/tagine-atlas',
  },
  {
    id: 'phosphate-kingdom',
    number: '052',
    title: 'The Phosphate Kingdom',
    category: 'Industrial Intelligence',
    description: 'Morocco holds 70% of world phosphate reserves. OCP Group, Khouribga mines, Jorf Lasfar processing, global fertilizer flows. $9.76B revenue.',
    tags: ['phosphate', 'ocp', 'mining', 'khouribga', 'fertilizer', 'jorf lasfar', 'industry', 'export', 'geology', 'agriculture'],
    href: '/data/phosphate-kingdom',
  },
  {
    id: 'anatomy-of-a-riad',
    number: '053',
    title: 'The Anatomy of a Riad',
    category: 'Architectural Intelligence',
    description: 'Courtyard, fountain, zellige, tadelakt, moucharabieh, cedar, gebs. 12 elements, 6 passive climate systems, 0 street-facing windows.',
    tags: ['riad', 'architecture', 'courtyard', 'zellige', 'tadelakt', 'moucharabieh', 'cedar', 'medina', 'house', 'islamic'],
    href: '/data/anatomy-of-a-riad',
  },
  {
    id: 'cannabis-rif',
    number: '054',
    title: 'Cannabis & the Rif',
    category: 'Economic Intelligence',
    description: 'The Rif Mountains produce 70% of Europe\'s hashish. 400,000+ people in the trade. Law 13-21 legalization. Sultan Hassan I to royal pardons.',
    tags: ['cannabis', 'rif', 'hashish', 'kif', 'ketama', 'legalization', 'agriculture', 'chefchaouen', 'economy', 'trade'],
    href: '/data/cannabis-rif',
  },
  {
    id: 'atlantic-coast',
    number: '059',
    title: 'The Atlantic Coast',
    category: 'Coastal Intelligence',
    description: 'Tangier to Dakhla. 3,500 km of coastline, 12 cities mapped. Fishing ports, wind energy, surf breaks, $1.6B Dakhla port.',
    tags: ['coast', 'atlantic', 'tangier', 'dakhla', 'fishing', 'wind', 'surf', 'port', 'essaouira', 'agadir'],
    href: '/data/atlantic-coast',
  },
  {
    id: 'tgv-rail-network',
    number: '060',
    title: 'The TGV & Rail Network',
    category: 'Infrastructure Intelligence',
    description: 'Africa\'s only high-speed rail. Al Boraq at 320 km/h. 55M passengers. ONCF conventional network. $9.5B 2040 strategy. Strait of Gibraltar tunnel.',
    tags: ['rail', 'tgv', 'al boraq', 'train', 'oncf', 'infrastructure', 'transport', 'high-speed', 'casablanca', 'tangier'],
    href: '/data/tgv-rail-network',
  },
]
