// ─────────────────────────────────────────────────
// DWL Search Index — 113 Data Modules
// Canonical numbering: 001–113
// ─────────────────────────────────────────────────

export interface SearchEntry {
  id: string
  number: string
  title: string
  category: string
  description: string
  tags: string[]
  href: string
}

export const SEARCH_INDEX: SearchEntry[] = [
  // ═══ 001–010 ═══
  { id: 'maghreb-compared', number: '001', title: 'The Maghreb Compared', category: 'Comparative', description: 'Morocco, Tunisia, and Algeria side by side. Population, GDP, tourism, investment, demographics.', tags: ['morocco', 'tunisia', 'algeria', 'gdp', 'population', 'comparison', 'north africa', 'maghreb', 'investment', 'development'], href: '/data/maghreb-compared' },
  { id: 'morocco-population', number: '002', title: 'Morocco Population Density', category: 'Urban Life', description: 'Mapbox heatmap of Morocco\'s 12 administrative regions. Population, density, urbanization rate.', tags: ['population', 'density', 'regions', 'urbanization', 'mapbox', 'casablanca', 'marrakech', 'map', 'demographics'], href: '/data/morocco-population' },
  { id: 'al-andalus', number: '003', title: 'The Al-Andalus Corridor', category: 'Culture & Identity', description: 'One continuous cultural bridge from Seville to Fes. Architecture, music, food, language — four layers of shared DNA.', tags: ['al-andalus', 'spain', 'seville', 'fes', 'architecture', 'music', 'food', 'language', 'flamenco', 'moorish', 'alhambra', 'córdoba'], href: '/data/al-andalus' },
  { id: 'morocco-economy', number: '004', title: 'Morocco Economy in One Page', category: 'Economy & Trade', description: 'GDP, exports, FDI, tourism, remittances, key sectors. The essential economic snapshot.', tags: ['gdp', 'economy', 'exports', 'fdi', 'tourism revenue', 'remittances', 'phosphate', 'automotive', 'world bank', 'imf'], href: '/data/morocco-economy' },
  { id: 'morocco-agriculture', number: '005', title: 'What Morocco Grows & Sends to the World', category: 'Food & Agriculture', description: 'Radial harvest wheel. Tomatoes, berries, citrus, olives, argan, seafood — ranked by export value.', tags: ['agriculture', 'exports', 'tomatoes', 'berries', 'citrus', 'olives', 'argan', 'seafood', 'farming', 'souss', 'harvest'], href: '/data/morocco-agriculture' },
  { id: 'water-crisis', number: '006', title: 'Morocco\'s Water Crisis', category: 'Geography & Environment', description: 'Reservoir levels, rainfall decline, desalination projects. The data behind Morocco\'s drought emergency.', tags: ['water', 'drought', 'reservoir', 'desalination', 'rainfall', 'agriculture', 'climate', 'dam', 'crisis'], href: '/data/water-crisis' },
  { id: 'dynasty-timeline', number: '007', title: 'The Dynasties of Morocco', category: 'History', description: 'Idrisids to Alaouites. 1,200 years of Moroccan rulers, capitals, and power shifts.', tags: ['dynasty', 'history', 'idrisids', 'almoravids', 'almohads', 'marinids', 'saadians', 'alaouites', 'sultan', 'king', 'fes', 'marrakech'], href: '/data/dynasty-timeline' },
  { id: 'seasonal-produce', number: '008', title: 'Seasonal Produce Wheel', category: 'Food & Agriculture', description: 'What\'s in season in Morocco month by month. Static interactive wheel with 30+ crops.', tags: ['seasonal', 'produce', 'food', 'vegetables', 'fruit', 'market', 'souk', 'cooking', 'season'], href: '/data/seasonal-produce' },
  { id: 'medina-atlas', number: '009', title: 'The Medina Atlas', category: 'Urban Life', description: 'Mapbox atlas of Morocco\'s historic medinas. Gates, fondouks, mosques, hammams, souks.', tags: ['medina', 'marrakech', 'fes', 'gates', 'bab', 'souk', 'fondouk', 'mosque', 'hammam', 'old city', 'urban'], href: '/data/medina-atlas' },
  { id: 'spice-map', number: '010', title: 'The Spice Map', category: 'Food & Agriculture', description: 'Morocco\'s spice geography. Ras el hanout, cumin, saffron, paprika — origins, routes, and uses.', tags: ['spice', 'ras el hanout', 'cumin', 'saffron', 'paprika', 'food', 'cooking', 'souk', 'market'], href: '/data/spice-map' },

  // ═══ 011–020 ═══
  { id: 'amazigh-identity', number: '011', title: 'Amazigh Identity Map', category: 'Culture & Identity', description: 'Berber-speaking regions, Tifinagh script distribution, tribal territories, and language survival. Three languages. Three ancient confederations. 3,000 years of script. From 45% to 24.8%.', tags: ['Amazigh', 'Berber', 'Tifinagh', 'Tashelhit', 'Tamazight', 'Tarifit', 'Rif', 'Souss', 'Middle Atlas', 'Anti-Atlas', 'IRCAM', 'Masmuda', 'Sanhaja', 'Zenata', 'confederation', 'tribe', 'language', 'script', 'Libyco-Berber', 'Neo-Tifinagh', 'Yennayer', 'Imazighen', 'census', 'decline', 'Arabization', 'indigenous', 'identity', 'Agadir Charter', 'Berber Spring', 'constitution 2011', 'Ghomara', 'Senhaja de Srair', 'Figuig', 'Judeo-Berber', 'Ait Atta', 'Ibn Khaldun', 'Almohad', 'Almoravid', 'Marinid'], href: '/data/amazigh-identity' },
  { id: 'phosphate-kingdom', number: '012', title: 'The Phosphate Kingdom', category: 'Economy & Trade', description: 'Morocco holds 70% of world phosphate reserves. OCP Group, Khouribga mines, Jorf Lasfar processing, global fertilizer flows.', tags: ['phosphate', 'ocp', 'mining', 'khouribga', 'fertilizer', 'jorf lasfar', 'industry', 'export', 'geology', 'agriculture'], href: '/data/phosphate-kingdom' },
  { id: 'moroccan-diaspora', number: '013', title: 'The Moroccan Diaspora', category: 'Demographics & Society', description: 'Where Moroccans live abroad. France, Spain, Italy, Netherlands, Belgium, Canada — remittance flows.', tags: ['diaspora', 'migration', 'remittances', 'france', 'spain', 'europe', 'mre', 'expatriate'], href: '/data/moroccan-diaspora' },
  { id: 'world-cup-2030', number: '014', title: '2030 World Cup Infrastructure', category: 'Tourism', description: 'Stadium builds, transport upgrades, hotel capacity, host city readiness for FIFA 2030.', tags: ['world cup', '2030', 'fifa', 'stadium', 'casablanca', 'rabat', 'marrakech', 'infrastructure', 'football'], href: '/data/world-cup-2030' },
  { id: 'tgv-rail-network', number: '015', title: 'The TGV & Rail Network', category: 'Infrastructure', description: 'Africa\'s only high-speed rail. Al Boraq at 320 km/h. 55M passengers. ONCF conventional network. $9.5B 2040 strategy.', tags: ['rail', 'tgv', 'al boraq', 'train', 'oncf', 'infrastructure', 'transport', 'high-speed', 'casablanca', 'tangier'], href: '/data/tgv-rail-network' },
  { id: 'solar-atlas', number: '016', title: 'Morocco\'s Solar Atlas', category: 'Energy', description: 'Noor Ouarzazate complex, MASEN solar projects, irradiance data by region, renewable energy targets, Xlinks subsea cable.', tags: ['solar', 'energy', 'renewable', 'Noor', 'Ouarzazate', 'MASEN', 'CSP', 'photovoltaic', 'irradiance', 'Xlinks', 'electricity'], href: '/data/solar-atlas' },
  { id: 'literary-morocco', number: '017', title: 'Literary Morocco', category: 'Culture & Identity', description: 'Writers who lived, wrote, or set stories in Morocco. Bowles, Burroughs, Choukri, Canetti, Mrabet, Genet, Eberhardt, Ben Jelloun.', tags: ['literature', 'writers', 'Bowles', 'Burroughs', 'Choukri', 'Canetti', 'Mrabet', 'Tangier', 'Interzone', 'Beat', 'books'], href: '/data/literary-morocco' },
  { id: 'geometry-of-zellige', number: '018', title: 'The Geometry of Zellige', category: 'Architecture & Design', description: 'Star patterns, tessellation, 17 wallpaper groups, compass-and-straightedge construction. The mathematics behind Moroccan tilework.', tags: ['zellige', 'geometry', 'mathematics', 'symmetry', 'tessellation', 'star', 'islamic', 'pattern', 'craft', 'tilework'], href: '/data/geometry-of-zellige' },
  { id: 'port-strategy', number: '019', title: 'Morocco\'s Port Strategy', category: 'Economy & Trade', description: 'Tanger Med, Nador West Med, Dakhla Atlantique, Casablanca, Jorf Lasfar. Container throughput, trade routes, Africa gateway.', tags: ['port', 'trade', 'Tanger Med', 'Nador', 'Dakhla', 'container', 'TEU', 'shipping', 'infrastructure', 'logistics', 'Africa'], href: '/data/port-strategy' },
  { id: 'carpet-atlas', number: '020', title: 'The Carpet Atlas', category: 'Craft & Textiles', description: 'Regional rug traditions mapped. Beni Ourain, Azilal, Boucherouite, Kilim, Hanbel — origins and motifs.', tags: ['carpet', 'rug', 'beni ourain', 'azilal', 'boucherouite', 'kilim', 'weaving', 'craft', 'atlas mountains'], href: '/data/carpet-atlas' },

  // ═══ 021–030 ═══
  { id: 'musical-traditions', number: '021', title: 'Morocco\'s Musical Traditions', category: 'Culture & Identity', description: 'Gnawa, Andalusi, Chaabi, Amazigh, Rai, Malhun, Sufi — eight traditions mapped. Instruments, regions, masters.', tags: ['music', 'gnawa', 'andalusi', 'chaabi', 'amazigh', 'rai', 'malhun', 'sufi', 'guembri', 'oud', 'bendir'], href: '/data/musical-traditions' },
  { id: 'olive-oil-economy', number: '022', title: 'The Olive Oil Economy', category: 'Food & Agriculture', description: 'Morocco\'s olive regions, production data, cooperatives, and export markets. Meknes, Fez, Marrakech terroirs.', tags: ['olive', 'oil', 'agriculture', 'meknes', 'cooperatives', 'exports', 'food', 'terroir'], href: '/data/olive-oil-economy' },
  { id: 'imperial-cities', number: '023', title: 'The Four Imperial Cities', category: 'History', description: 'Fes, Marrakech, Meknes, Rabat. Each dynasty chose its capital. The power map of Morocco.', tags: ['fes', 'marrakech', 'meknes', 'rabat', 'imperial', 'capital', 'dynasty', 'history'], href: '/data/imperial-cities' },
  { id: 'ramadan-moon', number: '024', title: 'Ramadan Moon', category: 'Living Data', description: 'Hijri calendar, prayer times, ftour traditions, Laylat al-Qadr countdown.', tags: ['ramadan', 'islam', 'prayer', 'fasting', 'ftour', 'mosque', 'calendar', 'hijri', 'moon'], href: '/data/ramadan-moon' },
  { id: 'trans-saharan-trade', number: '025', title: 'Trans-Saharan Trade Routes', category: 'History', description: 'Salt, gold, slaves, manuscripts. The ancient trade networks that built Timbuktu and Marrakech.', tags: ['sahara', 'trade', 'gold', 'salt', 'timbuktu', 'caravan', 'desert', 'trans-saharan'], href: '/data/trans-saharan-trade' },
  { id: 'argan-triangle', number: '026', title: 'The Argan Triangle', category: 'Geography & Environment', description: 'UNESCO biosphere reserve. The only place on earth argan trees grow. Cooperatives, cosmetics, cooking.', tags: ['argan', 'oil', 'souss', 'essaouira', 'cooperatives', 'women', 'unesco', 'cosmetics', 'tree'], href: '/data/argan-triangle' },
  { id: 'cinema-morocco', number: '027', title: 'Cinema Morocco', category: 'Culture & Identity', description: 'Ouarzazate studios, filmed-in-Morocco productions, Game of Thrones locations, Atlas Corporation.', tags: ['cinema', 'film', 'ouarzazate', 'gladiator', 'game of thrones', 'hollywood', 'studio', 'atlas'], href: '/data/cinema-morocco' },
  { id: 'moroccan-tea', number: '028', title: 'The Anatomy of Moroccan Tea', category: 'Food & Agriculture', description: 'Chinese gunpowder green tea, fresh mint, sugar. How it arrived, how it\'s made, why it matters.', tags: ['tea', 'mint', 'atay', 'ceremony', 'chinese', 'gunpowder', 'green tea', 'hospitality'], href: '/data/moroccan-tea' },
  { id: 'french-protectorate', number: '029', title: 'The French Protectorate', category: 'History', description: '1912–1956. Treaty of Fez, Lyautey, villes nouvelles, Rif War, Berber Dahir, Istiqlal, Mohammed V exile, independence.', tags: ['protectorate', 'France', 'Lyautey', 'Prost', 'ville nouvelle', 'colonialism', 'independence', 'Istiqlal', 'Mohammed V', 'Rif', 'Abd el-Krim', 'Treaty of Fez'], href: '/data/french-protectorate' },
  { id: 'hammam-culture', number: '030', title: 'Hammam Culture', category: 'Culture & Identity', description: 'The social architecture of the Moroccan bathhouse. Three rooms, six steps, five neighbourhood elements. Design, ritual, products.', tags: ['hammam', 'bathhouse', 'savon beldi', 'black soap', 'kessa', 'ghassoul', 'argan oil', 'ritual', 'ablution', 'mosque', 'medina', 'women', 'culture'], href: '/data/hammam-culture' },

  // ═══ 031–040 ═══
  { id: 'storks-eye-view', number: '031', title: 'A Stork\'s Eye View', category: 'Living Data', description: 'White stork migration, nesting colonies, Gibraltar flyway. Live migration status based on current month.', tags: ['stork', 'bird', 'migration', 'gibraltar', 'nesting', 'chellah', 'volubilis', 'wildlife'], href: '/data/storks-eye-view' },
  { id: 'anatomy-of-a-riad', number: '032', title: 'The Anatomy of a Riad', category: 'Architecture & Design', description: 'Courtyard, fountain, zellige, tadelakt, moucharabieh, cedar, gebs. 12 elements, 6 passive climate systems, 0 street-facing windows.', tags: ['riad', 'architecture', 'courtyard', 'zellige', 'tadelakt', 'moucharabieh', 'cedar', 'medina', 'house', 'islamic'], href: '/data/anatomy-of-a-riad' },
  { id: 'cannabis-rif', number: '033', title: 'Cannabis & the Rif', category: 'Economy & Trade', description: 'The Rif Mountains produce 70% of Europe\'s hashish. 400,000+ people in the trade. Law 13-21 legalization.', tags: ['cannabis', 'rif', 'hashish', 'kif', 'ketama', 'legalization', 'agriculture', 'chefchaouen', 'economy', 'trade'], href: '/data/cannabis-rif' },
  { id: 'atlantic-coast', number: '034', title: 'The Atlantic Coast', category: 'Geography & Environment', description: 'Tangier to Dakhla. 3,500 km of coastline, 12 cities mapped. Fishing ports, wind energy, surf breaks, $1.6B Dakhla port.', tags: ['coast', 'atlantic', 'tangier', 'dakhla', 'fishing', 'wind', 'surf', 'port', 'essaouira', 'agadir'], href: '/data/atlantic-coast' },
  { id: 'date-palm-oases', number: '035', title: 'The Date Palm Oases', category: 'Food & Agriculture', description: 'Draa Valley, Ziz Valley, Tafilalet. Three-tier oasis ecology, 453 cultivars, Bayoud disease, khettara irrigation.', tags: ['date palm', 'oasis', 'Draa', 'Ziz', 'Tafilalet', 'Mejhoul', 'Medjool', 'Bayoud', 'khettara', 'irrigation', 'desert', 'ecology'], href: '/data/date-palm-oases' },
  { id: 'tanneries', number: '036', title: 'The Tanneries', category: 'Craft & Textiles', description: 'Fez Chouara. 900 years of leather. 1,200 basins, pigeon dung, natural dyes. Process, labour, the 86 that became 3.', tags: ['tannery', 'Chouara', 'Fez', 'Fes', 'leather', 'dye', 'indigo', 'poppy', 'saffron', 'henna', 'babouche', 'craft', 'chromium', 'medina', 'guild'], href: '/data/tanneries' },
  { id: 'jewish-heritage', number: '037', title: 'Jewish Heritage in Morocco', category: 'Culture & Identity', description: '265,000 in 1948. ~1,000 in 2025. Mellahs, synagogues, cemeteries. Operation Yachin, Cadima, the departure, the preservation.', tags: ['Jewish', 'mellah', 'synagogue', 'Sephardic', 'Operation Yachin', 'Cadima', 'emigration', 'Israel', 'Fez', 'Marrakech', 'Essaouira', 'Mohammed V', 'heritage'], href: '/data/jewish-heritage' },
  { id: 'moroccan-fashion', number: '038', title: 'Moroccan Fashion Intelligence', category: 'Architecture & Design', description: 'Caftan, djellaba, babouche, takchita. Six core garments, three embroidery schools. UNESCO 2025. $4.25B textile industry.', tags: ['fashion', 'caftan', 'djellaba', 'babouche', 'takchita', 'sfifa', 'aakad', 'embroidery', 'Fez', 'Rabat', 'UNESCO', 'textile', 'designer', 'artisan', 'wedding'], href: '/data/moroccan-fashion' },
  { id: 'route-thousand-kasbahs', number: '039', title: 'The Route of a Thousand Kasbahs', category: 'Architecture & Design', description: 'Aït Benhaddou to Skoura. Fortified mud-brick architecture of the Drâa-Tafilalet. 4,000+ earthen settlements. Glaoui dynasty.', tags: ['kasbah', 'ksar', 'Ait Benhaddou', 'Telouet', 'Taourirt', 'Skoura', 'Ouarzazate', 'Glaoui', 'rammed earth', 'pisé', 'UNESCO', 'Draa-Tafilalet', 'Gladiator', 'Game of Thrones'], href: '/data/route-thousand-kasbahs' },
  { id: 'couscous-friday', number: '040', title: 'Couscous Friday', category: 'Food & Agriculture', description: 'The sacred Friday meal. Seven regional variations, three-steam technique, communal platter. UNESCO 2020.', tags: ['couscous', 'Friday', 'seksu', 'tfaya', 'seffa', 'UNESCO', 'Amazigh', 'communal', 'ritual', 'food', 'semolina', 'Ramadan', 'Maghreb'], href: '/data/couscous-friday' },

  // ═══ 041–050 ═══
  { id: 'weather-portraits', number: '041', title: 'Weather Portraits', category: 'Living Data', description: 'Live weather for 8 Moroccan cities. Open-Meteo integration, NASA satellite imagery toggle.', tags: ['weather', 'temperature', 'climate', 'satellite', 'nasa', 'live', 'marrakech', 'casablanca', 'rain'], href: '/data/weather-portraits' },
  { id: 'automotive-industry', number: '042', title: 'Morocco\'s Automotive Revolution', category: 'Economy & Trade', description: 'Renault Tangier, Stellantis Kenitra. How Morocco became Africa\'s #1 car producer.', tags: ['automotive', 'car', 'renault', 'stellantis', 'tangier', 'kenitra', 'industry', 'exports', 'manufacturing'], href: '/data/automotive-industry' },
  { id: 'tagine-atlas', number: '043', title: 'The Tagine Atlas', category: 'Food & Agriculture', description: 'Regional tagine variations mapped. Marrakech lamb-prune, Fes chicken-olive, coastal fish chermoula, Berber mountain.', tags: ['tagine', 'food', 'cooking', 'lamb', 'chicken', 'fish', 'spice', 'saffron', 'marrakech', 'fes'], href: '/data/tagine-atlas' },
  { id: 'atlas-mountains', number: '044', title: 'The Atlas Mountains', category: 'Geography & Environment', description: 'High Atlas, Middle Atlas, Anti-Atlas. Elevation profiles, Toubkal, ski stations, transhumance.', tags: ['atlas', 'mountains', 'toubkal', 'high atlas', 'trekking', 'ski', 'oukaimeden', 'imlil', 'berber'], href: '/data/atlas-mountains' },
  { id: 'bread-of-morocco', number: '045', title: 'The Bread of Morocco', category: 'Food & Agriculture', description: 'Khobz, msemen, baghrir, rghaif, harcha. Eight breads. Communal ovens. Wheat dependency — 60%+ imported. The sacred food.', tags: ['bread', 'khobz', 'msemen', 'baghrir', 'rghaif', 'harcha', 'ferran', 'oven', 'communal', 'wheat', 'flour', 'subsidy', 'food security'], href: '/data/bread-of-morocco' },
  { id: 'oldest-universities', number: '046', title: 'The World\'s Oldest Universities', category: 'Culture & Identity', description: 'Al-Qarawiyyin (859 CE). Founded by Fatima al-Fihri. Ben Youssef Madrasa. 229 years before Bologna.', tags: ['Al-Qarawiyyin', 'university', 'oldest', 'Fatima al-Fihri', 'Fez', 'madrasa', 'Ben Youssef', 'Marrakech', 'Bologna', 'Oxford', 'Maimonides', 'Ibn Khaldun', 'UNESCO'], href: '/data/oldest-universities' },
  { id: 'not-all-desert-is-sand', number: '047', title: 'Not All Desert Is Sand', category: 'Geography & Environment', description: 'Erg, reg, hammada, oued. Four desert types. Only 25% of the Sahara is sand. Erg Chebbi 150m dunes.', tags: ['desert', 'Sahara', 'erg', 'reg', 'hammada', 'oued', 'wadi', 'sand', 'dunes', 'Erg Chebbi', 'Merzouga', 'Erg Chegaga', 'geomorphology', 'arid'], href: '/data/not-all-desert-is-sand' },
  { id: 'surf-coast', number: '048', title: 'Morocco\'s Surf Coast', category: 'Geography & Environment', description: '15 surf breaks mapped from Safi to Essaouira. Swell data, season guide, and the economics of a 50,000-guest-per-year surf boom.', tags: ['surf', 'taghazout', 'imsouane', 'anchor point', 'sidi kaouki', 'waves', 'ocean', 'atlantic', 'beach', 'swell'], href: '/data/surf-coast' },
  { id: 'wedding-atlas', number: '049', title: 'The Moroccan Wedding', category: 'Tourism', description: 'Seven days, seven outfits. Henna night, hammam, amariya, negafa, the feast. Regional variations and cost breakdown.', tags: ['wedding', 'marriage', 'henna', 'negafa', 'amariya', 'caftan', 'ceremony', 'tradition', 'family', 'celebration'], href: '/data/wedding-atlas' },
  { id: 'souk-decoded', number: '050', title: 'The Souk Decoded', category: 'Urban Life', description: 'How a Moroccan market is organized. Guilds, pricing logic, negotiation patterns, spatial architecture.', tags: ['souk', 'market', 'medina', 'trade', 'guild', 'craft', 'negotiation', 'commerce', 'economy', 'marrakech'], href: '/data/souk-decoded' },

  // ═══ 051–058 ═══
  { id: 'pottery-traditions', number: '051', title: 'The Pottery Traditions', category: 'Craft & Textiles', description: 'Fes blue, Safi polychrome, Tamegroute green, Rif pottery. Regional ceramics mapped.', tags: ['pottery', 'ceramics', 'fes', 'safi', 'tamegroute', 'craft', 'blue', 'green', 'artisan'], href: '/data/pottery-traditions' },
  { id: 'before-the-sahara', number: '052', title: 'Before the Sahara', category: 'Geography & Environment', description: 'Desertification, NDVI vegetation data, oasis collapse, green belt projects. The land between Atlas and sand.', tags: ['desert', 'sahara', 'desertification', 'oasis', 'ndvi', 'vegetation', 'climate', 'drought', 'water', 'green wall'], href: '/data/before-the-sahara' },
  { id: 'harvest-calendar', number: '053', title: 'The Harvest Calendar', category: 'Living Data', description: 'A living clock of Moroccan agriculture. 32 crops, auto-highlights current month, play/pause.', tags: ['harvest', 'agriculture', 'seasonal', 'crops', 'farming', 'calendar', 'live', 'monthly', 'produce'], href: '/data/harvest-calendar' },
  { id: 'bird-atlas', number: '054', title: 'The Bird Atlas', category: 'Geography & Environment', description: 'North Africa\'s bird preservation areas and migration flyways. 27 IBAs, 3 flyways, 509 species.', tags: ['bird', 'migration', 'flyway', 'ibis', 'wildlife', 'nature', 'wetland', 'conservation', 'birdlife'], href: '/data/bird-atlas' },
  { id: 'islamic-spain', number: '055', title: 'Islamic Spain — 781 Years of Al-Andalus', category: 'History', description: 'From Tariq ibn Ziyad\'s 711 crossing to the fall of Granada. Vertical timeline and Mapbox map.', tags: ['al-andalus', 'spain', 'islamic', 'umayyad', 'córdoba', 'granada', 'alhambra', 'reconquista', 'history', '711', '1492', 'caliphate'], href: '/data/islamic-spain' },
  { id: 'the-gnawa-road', number: '120', title: 'The Gnawa Road', category: 'Sacred & Spiritual', description: 'From West Africa to Morocco to the world. Trans-Saharan slave routes. Guembri. Seven spirit colours. Lila ceremony. Maalem lineages. Source kingdoms. The diaspora: Stambali, Bori, Vodou, Candomblé, Santería — one root, many branches.', tags: ['Gnawa', 'Gnaoua', 'maalem', 'guembri', 'sintir', 'qraqeb', 'lila', 'derdeba', 'trance', 'jedba', 'mluk', 'spirits', 'Mahmoud Guinia', 'Essaouira', 'UNESCO', 'Sufi', 'slavery', 'West Africa', 'trans-Saharan', 'Bori', 'Stambali', 'Vodou', 'Candomblé', 'Santería', 'Hausa', 'Songhai', 'Timbuktu', 'diaspora', 'blues', 'jazz', 'Pharoah Sanders', 'Randy Weston'], href: '/data/the-gnawa-road' },
  { id: 'gardens-of-morocco', number: '057', title: 'The Gardens of Morocco', category: 'Geography & Environment', description: 'Majorelle, Agdal, Menara, Jnan Sbil. Islamic garden design. Khettara water systems. Almohad engineering. 500 hectares of productive paradise. Majorelle Blue #6050DC.', tags: ['garden', 'Majorelle', 'Agdal', 'Menara', 'Jnan Sbil', 'Marrakech', 'Fez', 'Islamic garden', 'chahar bagh', 'khettara', 'qanat', 'seguia', 'noria', 'water', 'irrigation', 'reservoir', 'Almohad', 'Yves Saint Laurent', 'Jacques Majorelle', 'Majorelle Blue', 'UNESCO', 'olive', 'orchard', 'pavilion', 'paradise', 'jannah', 'geometry', 'Berber Museum', 'Pierre Bergé'], href: '/data/gardens-of-morocco' },
  { id: 'migration-routes', number: '058', title: 'Migration Routes Through Morocco', category: 'Demographics & Society', description: 'Sub-Saharan migration corridors. Western Mediterranean and Atlantic routes. Ceuta and Melilla. Transit cities. SNIA policy. 10,457 dead or missing in 2024.', tags: ['migration', 'migrants', 'refugees', 'asylum', 'sub-Saharan', 'Africa', 'Spain', 'Ceuta', 'Melilla', 'Strait of Gibraltar', 'Canary Islands', 'Atlantic route', 'Western Mediterranean', 'Sahara', 'transit', 'Oujda', 'Nador', 'Tangier', 'SNIA', 'regularisation', 'EU', 'Frontex', 'IOM', 'UNHCR', 'Melilla massacre', 'border', 'fence', 'cayucos', 'Mohammed VI', 'deaths', 'Senegal', 'Mali'], href: '/data/migration-routes' },

  // ═══ 059+ ═══
  { id: 'waters-of-empire', number: '059', title: 'Waters of Empire', category: 'History', description: 'The hammam is not Arab. It is Roman — inherited, transformed, and kept alive while Europe forgot how to wash. 15 archaeological sites, 6 civilizations, 2,600 years. From thermae to hammam.', tags: ['hammam', 'Roman', 'thermae', 'bath', 'bathing', 'hypocaust', 'Volubilis', 'Carthage', 'Caracalla', 'Diocletian', 'Umayyad', 'Qusayr Amra', 'frigidarium', 'caldarium', 'tepidarium', 'Islam', 'ablution', 'wudu', 'ghusl', 'Jerash', 'Leptis Magna', 'Timgad', 'Banasa', 'Lixus', 'Palmyra', 'Bath', 'Trier', 'Ephesus', 'Ottoman', 'architecture', 'water', 'empire', 'al-Ghazali'], href: '/data/waters-of-empire' },
  { id: 'before-the-crescent', number: '060', title: 'Before the Crescent', category: 'History', description: '315,000 years of Morocco before Islam. Homo sapiens at Jebel Irhoud, Amazigh confederations, Phoenician traders, Carthage, Rome, Vandals, Byzantines. Six civilizations. The Amazigh outlasted them all.', tags: ['pre-Islamic', 'Jebel Irhoud', 'Homo sapiens', 'Amazigh', 'Berber', 'Phoenician', 'Carthage', 'Rome', 'Roman', 'Vandal', 'Byzantine', 'Volubilis', 'Lixus', 'Banasa', 'Juba II', 'Cleopatra', 'Mauretania', 'Tingitana', 'garum', 'olive oil', 'Christianity', 'Judaism', 'Kahina', 'Tifinagh', 'Masmuda', 'Sanhaja', 'Zenata', 'history', 'ancient', 'archaeology'], href: '/data/before-the-crescent' },

  // ═══ 061–070 ═══
  { id: 'gates-of-marrakech', number: '061', title: 'The 19 Gates of Marrakech', category: 'Architecture & Design', description: 'The gates and walls of the Marrakech medina. Each bab mapped with its history, construction date, and role in the city defence.', tags: ['gates', 'bab', 'Marrakech', 'medina', 'walls', 'ramparts', 'Almohad', 'urban', 'defence', 'archaeology', 'architecture'], href: '/data/gates-of-marrakech' },
  { id: 'almohad-atlas', number: '062', title: 'The Almohad Atlas', category: 'Architecture & Design', description: 'The Almohad Empire in stone. Caliphs, territories, monuments from Marrakech to Seville. The empire that built the Koutoubia, the Giralda, and the Hassan Tower.', tags: ['Almohad', 'empire', 'caliphate', 'Koutoubia', 'Giralda', 'Hassan Tower', 'Marrakech', 'Seville', 'Rabat', 'architecture', 'mosque', 'dynasty', 'ibn Tumart'], href: '/data/almohad-atlas' },
  { id: 'the-14-kilometres', number: '119', title: 'The 14 Kilometres', category: 'History & Migration', description: 'The Strait of Gibraltar is 14 km wide. In 711, armies crossed north. In 1492, refugees crossed south. In 2030, both shores host the World Cup. 800 years of human flow. Architecture, music, food, and language crossed in both directions. GDP per capita gap: 5.3×. The distance is nothing. The gap is everything.', tags: ['strait', 'Gibraltar', 'crossing', 'migration', 'Tariq', 'Spain', 'Morocco', 'Africa', 'Europe', 'Tangier', 'Andalusi', 'Moriscos', 'al-Andalus', 'Reconquista', 'World Cup 2030', 'GDP', 'inequality', 'comparison', 'Chefchaouen', 'Tetouan', 'Fes', 'Granada', 'Córdoba', 'Seville'], href: '/data/the-14-kilometres' },
  { id: 'reconquista-exodus', number: '064', title: 'The Reconquista Exodus', category: 'History', description: 'The Reconquista from 711 to 1614. The Christian reconquest of Iberia and the exodus of Muslims and Jews to Morocco and North Africa.', tags: ['Reconquista', 'exodus', 'Spain', 'al-Andalus', 'Moriscos', 'Jews', 'Sephardic', 'expulsion', 'Granada', '1492', 'Inquisition', 'Fez', 'Tétouan', 'Chefchaouen'], href: '/data/reconquista-exodus' },
  { id: 'jewish-atlas', number: '065', title: 'The Jewish Atlas', category: 'Sacred & Spiritual', description: 'Jewish Morocco. The Toshavim and Megorashim. Mellahs, synagogues, cemeteries, saints. 250,000 Jews in 1948. Fewer than 2,000 today.', tags: ['Jewish', 'mellah', 'synagogue', 'Toshavim', 'Megorashim', 'Sephardic', 'Israel', 'diaspora', 'Essaouira', 'Fez', 'Marrakech', 'heritage', 'cemetery', 'saint'], href: '/data/jewish-atlas' },
  { id: 'ottoman-north-africa', number: '066', title: 'The Ottoman Empire in North Africa', category: 'History', description: 'Why Morocco was the only North African country never conquered by the Ottomans. Ottoman territories, cities, and the Moroccan exception.', tags: ['Ottoman', 'empire', 'Tunisia', 'Algeria', 'Libya', 'Morocco', 'independence', 'Saadian', 'Battle of Three Kings', 'sultan', 'history'], href: '/data/ottoman-north-africa' },
  { id: 'dirhams-journey', number: '067', title: 'The Dirham\'s Journey', category: 'Economy & Trade', description: 'The Moroccan dirham through history. Currency, exchange rates, purchasing power, and economic transformation.', tags: ['dirham', 'currency', 'money', 'exchange rate', 'economy', 'MAD', 'Bank al-Maghrib', 'purchasing power', 'inflation'], href: '/data/dirhams-journey' },
  { id: 'africa-rising', number: '068', title: 'Africa Rising', category: 'Economy & Trade', description: 'Morocco ranked among 54 African nations. Bump chart showing competitiveness across GDP, tourism, infrastructure, education, and investment.', tags: ['Africa', 'ranking', 'competitiveness', 'GDP', 'tourism', 'infrastructure', 'investment', 'continent', 'comparison', 'bump chart'], href: '/data/africa-rising' },

  { id: 'morocco-3d-population', number: '070', title: 'Morocco Population Density 3D', category: 'Urban Life', description: 'Morocco population density as a 3D bar map. Each grid cell extruded by people per square kilometre. The Atlantic corridor, the empty Sahara, the Casablanca megacity.', tags: ['population', '3D', 'density', 'map', 'Casablanca', 'Atlantic', 'Sahara', 'interactive', 'demographics', 'urbanization'], href: '/data/morocco-3d-population' },

  // ═══ 071–080 ═══
  { id: 'tourism-flow', number: '071', title: 'Where 17.4 Million Tourists Go', category: 'Tourism', description: 'Morocco tourism flow: source countries → airports → destinations → spending. 17.4 million visitors in 2024, 112 billion MAD revenue.', tags: ['tourism', 'flow', 'visitors', 'airports', 'destinations', 'spending', 'revenue', 'Marrakech', 'Agadir', 'Fez', 'Sankey', 'arrivals'], href: '/data/tourism-flow' },
  { id: 'the-build', number: '072', title: 'The Build', category: 'Infrastructure', description: 'Watch Morocco construct itself. 27 years of infrastructure: highways, rail, airports, hotels, tourist arrivals. Animated timeline from 2004–2030.', tags: ['infrastructure', 'highways', 'TGV', 'airports', 'hotels', 'construction', 'timeline', 'development', 'investment', '2030'], href: '/data/the-build' },
  { id: 'wind-and-sun', number: '073', title: 'Wind & Sun', category: 'Energy', description: 'Morocco renewable energy installations mapped as radial blooms. 14 solar, wind, and hydro plants. 3.8GW installed. 52% renewable target by 2030.', tags: ['renewable', 'solar', 'wind', 'energy', 'Noor', 'Ouarzazate', 'Tarfaya', 'hydro', 'radial', 'sustainability', 'green'], href: '/data/wind-and-sun' },
  { id: 'carpet-code', number: '074', title: 'The Carpet Code', category: 'Craft & Textiles', description: 'Moroccan carpet traditions decoded. Tribal motifs, weaving techniques, regional styles. The visual language of the loom.', tags: ['carpet', 'rug', 'textile', 'weaving', 'tribal', 'motif', 'Beni Ourain', 'Azilal', 'kilim', 'Amazigh', 'craft', 'pattern'], href: '/data/carpet-code' },
  { id: 'carthage', number: '075', title: 'Carthage Must Be Destroyed', category: 'History', description: 'The Carthaginian Empire. Punic Wars, trade routes, North African territories. From Hannibal to the fall. Mapped and told.', tags: ['Carthage', 'Punic', 'Hannibal', 'Rome', 'Tunisia', 'trade', 'Mediterranean', 'war', 'ancient', 'archaeology', 'Phoenician'], href: '/data/carthage' },
  { id: 'rome-north-africa', number: '076', title: 'Rome in North Africa', category: 'History', description: 'The Roman Empire across North Africa. From Tangier to Cyrene. Provinces, cities, monuments, trade routes. Mapbox and timeline.', tags: ['Rome', 'Roman', 'North Africa', 'province', 'Leptis Magna', 'Carthage', 'Volubilis', 'Timgad', 'archaeology', 'empire', 'map'], href: '/data/rome-north-africa' },
  { id: 'roma-africana', number: '077', title: 'Roma Africana', category: 'History', description: 'Roman Africa — the complete imperial footprint. From Tangier to Cyrene. Cities, trade, grain, gladiators, and the provinces that fed Rome.', tags: ['Rome', 'Africa', 'province', 'grain', 'trade', 'Leptis', 'Carthage', 'Mediterranean', 'empire', 'map', 'history'], href: '/data/roma-africana' },
  { id: 'chameleon-country', number: '078', title: 'The Chameleon Country', category: 'Culture & Identity', description: 'Morocco changes colour depending on where you stand. 12 regions, each with its own identity, economy, and personality. Cultural cartography.', tags: ['regions', 'Casablanca', 'Marrakech', 'Fez', 'Tangier', 'Agadir', 'identity', 'culture', 'diversity', 'cartography'], href: '/data/chameleon-country' },
  { id: 'colour-index', number: '079', title: 'The Colour Index', category: 'Architecture & Design', description: 'Morocco in pigments. Majorelle blue, saffron yellow, Tamegroute green, henna red. The cultural meaning of every colour mapped to its source.', tags: ['colour', 'color', 'pigment', 'Majorelle blue', 'saffron', 'Tamegroute green', 'henna', 'indigo', 'design', 'craft', 'dye'], href: '/data/colour-index' },
  { id: 'demographic-atlas', number: '080', title: 'The Demographic Atlas', category: 'Demographics & Society', description: 'Morocco demographics by region. Population growth, urbanization, illiteracy, youth bulge. The numbers behind the map.', tags: ['demographics', 'population', 'growth', 'urbanization', 'illiteracy', 'youth', 'regions', 'census', 'fertility', 'age'], href: '/data/demographic-atlas' },

  // ═══ 081–090 ═══
  { id: 'digital-zellige', number: '081', title: 'Digital Zellige', category: 'Architecture & Design', description: 'Zellige in the digital age. Geometric patterns, mathematical principles, and the American pivot towards Moroccan tilework.', tags: ['zellige', 'tile', 'geometry', 'pattern', 'Islamic', 'design', 'mosaic', 'Fez', 'craft', 'mathematics', 'digital'], href: '/data/digital-zellige' },
  { id: 'four-peaks', number: '082', title: 'Four Peaks', category: 'Geography & Environment', description: 'Morocco\'s highest mountains. Toubkal, M\'Goun, Ayachi, Sirwa. Elevation profiles, geography, and scale comparison.', tags: ['mountains', 'Toubkal', 'Atlas', 'High Atlas', 'elevation', 'geography', 'peak', 'trekking', 'summit'], href: '/data/four-peaks' },
  { id: 'geometry-of-culture', number: '083', title: 'The Geometry of Culture', category: 'Architecture & Design', description: 'The six star families of Islamic geometric art. Mathematical construction, cultural meaning, and Moroccan applications.', tags: ['geometry', 'Islamic art', 'star', 'pattern', 'mathematics', 'zellige', 'arabesque', 'construction', 'symmetry'], href: '/data/geometry-of-culture' },

  { id: 'hammam-geometry', number: '085', title: 'The Hammam Geometry', category: 'Architecture & Design', description: 'The architectural geometry of the Moroccan hammam. Floor plan, hypocaust system, dome oculi, heat flow. Engineering diagram.', tags: ['hammam', 'architecture', 'geometry', 'hypocaust', 'dome', 'bath', 'floor plan', 'engineering', 'heat'], href: '/data/hammam-geometry' },
  { id: 'high-speed-horizon', number: '086', title: 'The High-Speed Horizon', category: 'Infrastructure', description: 'Morocco\'s high-speed rail network. Al Boraq and the melting map of travel times. How TGV shrinks distance.', tags: ['TGV', 'Al Boraq', 'rail', 'train', 'high-speed', 'infrastructure', 'Casablanca', 'Tangier', 'travel time', 'transport'], href: '/data/high-speed-horizon' },
  { id: 'languages-of-morocco', number: '087', title: 'The Languages of Morocco', category: 'Culture & Identity', description: 'Darija, Tashelhit, Tamazight, Tarifit, French, Spanish, English. The linguistic landscape of Morocco mapped.', tags: ['language', 'Darija', 'Arabic', 'Amazigh', 'French', 'Spanish', 'Tashelhit', 'Tamazight', 'Tarifit', 'linguistics', 'map'], href: '/data/languages-of-morocco' },
  { id: 'marriage-economy', number: '088', title: 'The Marriage Economy', category: 'Demographics & Society', description: 'The economics of Moroccan marriage. Mahr, trousseau, ceremony costs, regional variations. What a wedding really costs.', tags: ['marriage', 'wedding', 'mahr', 'dowry', 'economy', 'cost', 'ceremony', 'social', 'family', 'tradition'], href: '/data/marriage-economy' },
  { id: 'marriage-equation', number: '089', title: 'The Marriage Equation', category: 'Demographics & Society', description: 'Marriage and divorce in Morocco. Rates, trends, regional data. The shifting equation of Moroccan family life.', tags: ['marriage', 'divorce', 'family', 'statistics', 'trends', 'Moudawana', 'women', 'social', 'demographics'], href: '/data/marriage-equation' },
  { id: 'medina-data', number: '090', title: 'The Medina Data', category: 'Infrastructure', description: 'Medina infrastructure mapped. Seven concentric rings from the mosque to the gates. Density, services, commerce, craft.', tags: ['medina', 'data', 'infrastructure', 'rings', 'mosque', 'souk', 'craft', 'density', 'urban', 'mapping'], href: '/data/medina-data' },

  // ═══ 091–100 ═══
  { id: 'moroccan-calendar', number: '091', title: 'The Moroccan Calendar', category: 'Culture & Identity', description: 'Three calendars in one country. Gregorian, Hijri, Amazigh. Festivals, harvests, and sacred dates mapped through the year.', tags: ['calendar', 'Hijri', 'Amazigh', 'Gregorian', 'festivals', 'Ramadan', 'Yennayer', 'Eid', 'harvest', 'dates', 'time'], href: '/data/moroccan-calendar' },
  { id: 'moroccan-genome', number: '092', title: 'The Moroccan Genome', category: 'Demographics & Society', description: 'The genetic ancestry of Morocco. E-M81 haplogroup, Amazigh DNA, admixture analysis. What the genome reveals about 315,000 years of migration.', tags: ['genome', 'DNA', 'genetics', 'E-M81', 'haplogroup', 'Amazigh', 'ancestry', 'admixture', 'migration', 'population'], href: '/data/moroccan-genome' },
  { id: 'seven-saints', number: '093', title: 'The Seven Saints of Marrakech', category: 'Sacred & Spiritual', description: 'Sab\'atou Rijāl — the seven patron saints of Marrakech. The ziyara pilgrimage circuit mapped. Sufi history and sacred sites.', tags: ['saints', 'Sufi', 'Marrakech', 'ziyara', 'pilgrimage', 'sacred', 'mosque', 'tomb', 'baraka', 'spiritual'], href: '/data/seven-saints' },
  { id: 'zaouia-map', number: '094', title: 'The Zaouia Map', category: 'Sacred & Spiritual', description: 'The Sufi geography of Morocco. Zaouias, brotherhoods, spiritual centres. The invisible architecture of faith.', tags: ['zaouia', 'Sufi', 'brotherhood', 'Tijani', 'Qadiri', 'Boutchichi', 'spiritual', 'sacred', 'map', 'faith'], href: '/data/zaouia-map' },
  { id: 'scent-atlas', number: '095', title: 'The Scent Atlas', category: 'Culture & Identity', description: 'Morocco in scent. Rose water, orange blossom, cedar, argan, oud. Source, chemistry, and the olfactory map of the country.', tags: ['scent', 'perfume', 'rose', 'orange blossom', 'cedar', 'argan', 'oud', 'attar', 'olfactory', 'sensory'], href: '/data/scent-atlas' },
  { id: 'shadow-moucharabieh', number: '096', title: 'The Shadow of the Moucharabieh', category: 'Architecture & Design', description: 'The moucharabieh — carved wooden screens that filter light and cool air. Traditional passive cooling vs modern heat. Architecture as climate control.', tags: ['moucharabieh', 'mashrabiya', 'screen', 'shadow', 'cooling', 'ventilation', 'architecture', 'light', 'craft', 'wood'], href: '/data/shadow-moucharabieh' },
  { id: 'solar-compass', number: '097', title: 'The Solar Compass', category: 'Energy', description: 'Noor-Ouarzazate and Morocco\'s concentrated solar power. Molten salt storage, MW output, the mechanics of solar energy in the Sahara.', tags: ['solar', 'Noor', 'Ouarzazate', 'CSP', 'concentrated', 'molten salt', 'energy', 'renewable', 'Sahara', 'power'], href: '/data/solar-compass' },
  { id: 'spice-routes', number: '098', title: 'The Spice Routes', category: 'Food & Agriculture', description: 'Morocco\'s spice geography expanded. Origin, season, volume, and the trade routes that brought each spice to the souk.', tags: ['spice', 'trade', 'route', 'cumin', 'saffron', 'paprika', 'cinnamon', 'souk', 'food', 'import', 'season'], href: '/data/spice-routes' },
  { id: 'tea-ceremony', number: '099', title: 'The Tea Ceremony Topology', category: 'Food & Agriculture', description: 'The six steps of Moroccan tea. Gunpowder green, fresh mint, sugar. A topology of the ceremony that runs the country.', tags: ['tea', 'ceremony', 'mint', 'gunpowder', 'sugar', 'atay', 'ritual', 'hospitality', 'food', 'culture'], href: '/data/tea-ceremony' },
  { id: 'the-empty-quarter', number: '100', title: 'The Empty Quarter', category: 'Geography & Environment', description: 'The Saharan nations compared. Morocco, Algeria, Libya, Egypt, Mauritania. How much of each country is desert. The empty quarter of North Africa.', tags: ['Sahara', 'desert', 'empty', 'Algeria', 'Libya', 'Egypt', 'Mauritania', 'comparison', 'geography', 'area'], href: '/data/the-empty-quarter' },

  // ═══ 101–112 ═══
  { id: 'the-free-people', number: '101', title: 'The Free People', category: 'Culture & Identity', description: 'The Amazigh mapped. Language, territory, identity. The indigenous people who outlasted every empire.', tags: ['Amazigh', 'Berber', 'free people', 'language', 'territory', 'identity', 'map', 'indigenous', 'Tifinagh'], href: '/data/the-free-people' },
  { id: 'the-long-rise', number: '102', title: 'The Long Rise', category: 'Tourism', description: 'Morocco tourism arrivals and revenue over time. The long rise from 2 million to 17 million visitors. Growth charted.', tags: ['tourism', 'arrivals', 'revenue', 'growth', 'chart', 'visitors', 'history', 'trend', 'development'], href: '/data/the-long-rise' },
  { id: 'the-nomad-pulse', number: '103', title: 'The Nomad Pulse', category: 'Living Data', description: 'Digital nomads in Morocco. Co-living, remote work infrastructure, visa policy. The pulse of the mobile workforce 2025–2026.', tags: ['nomad', 'digital', 'remote work', 'co-living', 'visa', 'Marrakech', 'Essaouira', 'Tangier', 'wifi', 'expat'], href: '/data/the-nomad-pulse' },
  { id: 'timeline-of-morocco', number: '104', title: 'Timeline of Morocco', category: 'History', description: 'The complete timeline of Morocco. From Jebel Irhoud to the present. Every dynasty, every turning point, every layer.', tags: ['timeline', 'history', 'dynasty', 'chronology', 'complete', 'Idrisid', 'Almoravid', 'Almohad', 'Marinid', 'Saadian', 'Alaouite'], href: '/data/timeline-of-morocco' },
  { id: 'water-equation', number: '105', title: 'The Water Equation', category: 'Geography & Environment', description: 'Dam storage, aquifer depletion, river basin fill rates. The water equation Morocco must solve before 2030.', tags: ['water', 'dam', 'aquifer', 'depletion', 'drought', 'river', 'storage', 'desalination', 'crisis', 'equation'], href: '/data/water-equation' },
  { id: 'who-is-the-goat', number: '106', title: 'Who Is the GOAT?', category: 'History', description: 'Marco Polo vs Ibn Battuta. Two travellers, two centuries, two journeys. Who covered more ground? The data decides.', tags: ['Ibn Battuta', 'Marco Polo', 'travel', 'explorer', 'comparison', 'GOAT', 'journey', 'distance', 'medieval', 'Tangier'], href: '/data/who-is-the-goat' },
  { id: 'wildlife-atlas', number: '107', title: 'The Wildlife Atlas', category: 'Geography & Environment', description: 'Morocco\'s wildlife mapped. Endangered species, national parks, habitats. From Barbary macaque to Saharan cheetah.', tags: ['wildlife', 'animals', 'endangered', 'national park', 'Barbary macaque', 'habitat', 'conservation', 'nature', 'atlas'], href: '/data/wildlife-atlas' },
  { id: 'world-cup-blueprint', number: '108', title: 'The World Cup Blueprint', category: 'Infrastructure', description: 'Morocco\'s 2030 World Cup infrastructure plan. Stadium builds, hotel rooms, jobs, investment. The economic blueprint.', tags: ['World Cup', '2030', 'stadium', 'infrastructure', 'FIFA', 'investment', 'jobs', 'hotels', 'construction', 'economic'], href: '/data/world-cup-blueprint' },
  { id: 'alphabet-of-craft', number: '109', title: 'The Moroccan Alphabet of Craft', category: 'Craft & Textiles', description: 'Morocco\'s craft traditions from A to Z. Each letter, a material. Each material, a region. The alphabet of making.', tags: ['craft', 'alphabet', 'artisan', 'pottery', 'leather', 'metal', 'wood', 'textile', 'tradition', 'handmade'], href: '/data/alphabet-of-craft' },
  { id: 'argan-constellation', number: '110', title: 'The Argan Constellation', category: 'Economy & Trade', description: 'Argan oil extraction: every manual step mapped. The labour, the cooperatives, the women. Sustainability and the argan triangle.', tags: ['argan', 'oil', 'cooperative', 'women', 'labour', 'Souss', 'sustainability', 'extraction', 'UNESCO', 'tree'], href: '/data/argan-constellation' },
  { id: 'calendar-of-light', number: '111', title: 'The Calendar of Light', category: 'Living Data', description: 'Daylight hours by month across Morocco. Latitude, solar angle, golden hour. The astronomical calendar that shapes daily life.', tags: ['daylight', 'light', 'solar', 'astronomy', 'latitude', 'golden hour', 'calendar', 'sun', 'season', 'photography'], href: '/data/calendar-of-light' },
  { id: 'pulse-medina', number: '112', title: 'The Pulse of the Medina', category: 'Urban Life', description: 'The medina as a living organism. Activity patterns, foot traffic, commerce rhythms. How the old city breathes through the day.', tags: ['medina', 'pulse', 'activity', 'foot traffic', 'commerce', 'rhythm', 'urban', 'daily life', 'pattern', 'living'], href: '/data/pulse-medina' },
  { id: 'the-apothecary', number: '113', title: 'The Apothecary', category: 'Food & Agriculture', description: 'Morocco\'s living pharmacopoeia. 7,000 plant species, 800 medicinal, 1,118 remedies catalogued. The attar, the scholarly lineage from Ibn al-Baytar to Bellakhdar, and why the knowledge is vanishing.', tags: ['herbalism', 'attar', 'medicinal plants', 'pharmacopoeia', 'herbs', 'spices', 'Bellakhdar', 'Ibn al-Baytar', 'traditional medicine', 'Lamiaceae', 'oregano', 'thyme', 'rosemary', 'lavender', 'mint', 'saffron', 'argan', 'Nigella', 'cumin', 'ethnobotany', 'Darija', 'souk', 'roots', 'laaroug'], href: '/data/the-apothecary' },
  { id: 'dust-that-feeds', number: '114', title: 'The Dust That Feeds', category: 'Geography & Environment', description: '182 million tons of Saharan dust cross the Atlantic every year. 27.7 million tons fall on the Amazon. 22,000 tons of phosphorus replace exactly what the rainforest loses to rain. The dead life of an ancient African lake feeds the largest living forest on earth.', tags: ['Sahara', 'Amazon', 'dust', 'phosphorus', 'Bodele', 'Chad', 'CALIPSO', 'NASA', 'trade winds', 'Atlantic', 'fertiliser', 'diatoms', 'Mega-Lake Chad', 'earth systems', 'climate', 'deforestation', 'nutrient cycle', 'iron', 'aerosol', 'trans-Atlantic'], href: '/data/dust-that-feeds' },
  { id: 'phosphate-equation', number: '115', title: 'The Phosphate Equation', category: 'Economy & Trade', description: "Morocco holds 50 billion metric tons of phosphate rock — 70% of the world's reserves. No substitute exists. Without phosphorus, nothing grows. OCP Group: $9.8B revenue, world's largest fertiliser complex, 1,300 years of reserves.", tags: ['phosphate', 'OCP', 'fertiliser', 'reserves', 'mining', 'Khouribga', 'Jorf Lasfar', 'geopolitics', 'food security', 'phosphorus', 'NPK', 'agriculture', 'Western Sahara', 'Africa', 'Brazil', 'India', 'diplomacy', 'monopoly'], href: '/data/phosphate-equation' },
  { id: 'sardine-current', number: '116', title: 'The Sardine Current', category: 'Geography & Environment', description: "The Canary Current runs 5,000 km from Portugal to Senegal — one of four major upwelling systems on earth. Morocco is the world's largest sardine exporter. Portugal's catch crashed 84%. Senegal's artisanal fishermen feed millions. One current, eight nations, no shared management.", tags: ['Canary Current', 'sardine', 'upwelling', 'Portugal', 'Morocco', 'Senegal', 'Mauritania', 'fisheries', 'Safi', 'Agadir', 'Dakhla', 'Peniche', 'Dakar', 'Atlantic', 'ocean', 'canning', 'EU fishing', 'climate', 'sardinella', 'food security', 'Phoenician'], href: '/data/sardine-current' },
]
