// ─────────────────────────────────────────────────
// DWL Search Index — 58 Data Modules
// Canonical numbering: 001–058, no gaps, no duplicates
// ─────────────────────────────────────────────────

export interface SearchEntry {
  id: string
  number: string
  title: string
  category: string
  description: string
  tags: string[]
  href: string
}

export const SEARCH_INDEX: SearchEntry[] = [
  // ═══ 001–010 ═══
  { id: 'maghreb-compared', number: '001', title: 'The Maghreb Compared', category: 'Comparative Analysis', description: 'Morocco, Tunisia, and Algeria side by side. Population, GDP, tourism, investment, demographics.', tags: ['morocco', 'tunisia', 'algeria', 'gdp', 'population', 'comparison', 'north africa', 'maghreb', 'investment', 'development'], href: '/data/maghreb-compared' },
  { id: 'morocco-population', number: '002', title: 'Morocco Population Density', category: 'Interactive Map', description: 'Mapbox heatmap of Morocco\'s 12 administrative regions. Population, density, urbanization rate.', tags: ['population', 'density', 'regions', 'urbanization', 'mapbox', 'casablanca', 'marrakech', 'map', 'demographics'], href: '/data/morocco-population' },
  { id: 'al-andalus', number: '003', title: 'The Al-Andalus Corridor', category: 'Cultural Geography', description: 'One continuous cultural bridge from Seville to Fes. Architecture, music, food, language — four layers of shared DNA.', tags: ['al-andalus', 'spain', 'seville', 'fes', 'architecture', 'music', 'food', 'language', 'flamenco', 'moorish', 'alhambra', 'córdoba'], href: '/data/al-andalus' },
  { id: 'morocco-economy', number: '004', title: 'Morocco Economy in One Page', category: 'Economic Intelligence', description: 'GDP, exports, FDI, tourism, remittances, key sectors. The essential economic snapshot.', tags: ['gdp', 'economy', 'exports', 'fdi', 'tourism revenue', 'remittances', 'phosphate', 'automotive', 'world bank', 'imf'], href: '/data/morocco-economy' },
  { id: 'morocco-agriculture', number: '005', title: 'What Morocco Grows & Sends to the World', category: 'Illustrated Data', description: 'Radial harvest wheel. Tomatoes, berries, citrus, olives, argan, seafood — ranked by export value.', tags: ['agriculture', 'exports', 'tomatoes', 'berries', 'citrus', 'olives', 'argan', 'seafood', 'farming', 'souss', 'harvest'], href: '/data/morocco-agriculture' },
  { id: 'water-crisis', number: '006', title: 'Morocco\'s Water Crisis', category: 'Environmental Data', description: 'Reservoir levels, rainfall decline, desalination projects. The data behind Morocco\'s drought emergency.', tags: ['water', 'drought', 'reservoir', 'desalination', 'rainfall', 'agriculture', 'climate', 'dam', 'crisis'], href: '/data/water-crisis' },
  { id: 'dynasty-timeline', number: '007', title: 'The Dynasties of Morocco', category: 'Historical Timeline', description: 'Idrisids to Alaouites. 1,200 years of Moroccan rulers, capitals, and power shifts.', tags: ['dynasty', 'history', 'idrisids', 'almoravids', 'almohads', 'marinids', 'saadians', 'alaouites', 'sultan', 'king', 'fes', 'marrakech'], href: '/data/dynasty-timeline' },
  { id: 'seasonal-produce', number: '008', title: 'Seasonal Produce Wheel', category: 'Food Intelligence', description: 'What\'s in season in Morocco month by month. Static interactive wheel with 30+ crops.', tags: ['seasonal', 'produce', 'food', 'vegetables', 'fruit', 'market', 'souk', 'cooking', 'season'], href: '/data/seasonal-produce' },
  { id: 'medina-atlas', number: '009', title: 'The Medina Atlas', category: 'Urban Geography', description: 'Mapbox atlas of Morocco\'s historic medinas. Gates, fondouks, mosques, hammams, souks.', tags: ['medina', 'marrakech', 'fes', 'gates', 'bab', 'souk', 'fondouk', 'mosque', 'hammam', 'old city', 'urban'], href: '/data/medina-atlas' },
  { id: 'spice-map', number: '010', title: 'The Spice Map', category: 'Food Intelligence', description: 'Morocco\'s spice geography. Ras el hanout, cumin, saffron, paprika — origins, routes, and uses.', tags: ['spice', 'ras el hanout', 'cumin', 'saffron', 'paprika', 'food', 'cooking', 'souk', 'market'], href: '/data/spice-map' },

  // ═══ 011–020 ═══
  { id: 'amazigh-identity', number: '011', title: 'Amazigh Identity Map', category: 'Cultural & Linguistic Intelligence', description: 'Berber-speaking regions, Tifinagh script distribution, tribal territories, and language survival. Three languages. Three ancient confederations. 3,000 years of script. From 45% to 24.8%.', tags: ['Amazigh', 'Berber', 'Tifinagh', 'Tashelhit', 'Tamazight', 'Tarifit', 'Rif', 'Souss', 'Middle Atlas', 'Anti-Atlas', 'IRCAM', 'Masmuda', 'Sanhaja', 'Zenata', 'confederation', 'tribe', 'language', 'script', 'Libyco-Berber', 'Neo-Tifinagh', 'Yennayer', 'Imazighen', 'census', 'decline', 'Arabization', 'indigenous', 'identity', 'Agadir Charter', 'Berber Spring', 'constitution 2011', 'Ghomara', 'Senhaja de Srair', 'Figuig', 'Judeo-Berber', 'Ait Atta', 'Ibn Khaldun', 'Almohad', 'Almoravid', 'Marinid'], href: '/data/amazigh-identity' },
  { id: 'phosphate-kingdom', number: '012', title: 'The Phosphate Kingdom', category: 'Industrial Intelligence', description: 'Morocco holds 70% of world phosphate reserves. OCP Group, Khouribga mines, Jorf Lasfar processing, global fertilizer flows.', tags: ['phosphate', 'ocp', 'mining', 'khouribga', 'fertilizer', 'jorf lasfar', 'industry', 'export', 'geology', 'agriculture'], href: '/data/phosphate-kingdom' },
  { id: 'moroccan-diaspora', number: '013', title: 'The Moroccan Diaspora', category: 'Demographics', description: 'Where Moroccans live abroad. France, Spain, Italy, Netherlands, Belgium, Canada — remittance flows.', tags: ['diaspora', 'migration', 'remittances', 'france', 'spain', 'europe', 'mre', 'expatriate'], href: '/data/moroccan-diaspora' },
  { id: 'world-cup-2030', number: '014', title: '2030 World Cup Infrastructure', category: 'Event Intelligence', description: 'Stadium builds, transport upgrades, hotel capacity, host city readiness for FIFA 2030.', tags: ['world cup', '2030', 'fifa', 'stadium', 'casablanca', 'rabat', 'marrakech', 'infrastructure', 'football'], href: '/data/world-cup-2030' },
  { id: 'tgv-rail-network', number: '015', title: 'The TGV & Rail Network', category: 'Infrastructure Intelligence', description: 'Africa\'s only high-speed rail. Al Boraq at 320 km/h. 55M passengers. ONCF conventional network. $9.5B 2040 strategy.', tags: ['rail', 'tgv', 'al boraq', 'train', 'oncf', 'infrastructure', 'transport', 'high-speed', 'casablanca', 'tangier'], href: '/data/tgv-rail-network' },
  { id: 'solar-atlas', number: '016', title: 'Morocco\'s Solar Atlas', category: 'Energy Intelligence', description: 'Noor Ouarzazate complex, MASEN solar projects, irradiance data by region, renewable energy targets, Xlinks subsea cable.', tags: ['solar', 'energy', 'renewable', 'Noor', 'Ouarzazate', 'MASEN', 'CSP', 'photovoltaic', 'irradiance', 'Xlinks', 'electricity'], href: '/data/solar-atlas' },
  { id: 'literary-morocco', number: '017', title: 'Literary Morocco', category: 'Cultural Intelligence', description: 'Writers who lived, wrote, or set stories in Morocco. Bowles, Burroughs, Choukri, Canetti, Mrabet, Genet, Eberhardt, Ben Jelloun.', tags: ['literature', 'writers', 'Bowles', 'Burroughs', 'Choukri', 'Canetti', 'Mrabet', 'Tangier', 'Interzone', 'Beat', 'books'], href: '/data/literary-morocco' },
  { id: 'geometry-of-zellige', number: '018', title: 'The Geometry of Zellige', category: 'Mathematical Intelligence', description: 'Star patterns, tessellation, 17 wallpaper groups, compass-and-straightedge construction. The mathematics behind Moroccan tilework.', tags: ['zellige', 'geometry', 'mathematics', 'symmetry', 'tessellation', 'star', 'islamic', 'pattern', 'craft', 'tilework'], href: '/data/geometry-of-zellige' },
  { id: 'port-strategy', number: '019', title: 'Morocco\'s Port Strategy', category: 'Trade & Infrastructure Intelligence', description: 'Tanger Med, Nador West Med, Dakhla Atlantique, Casablanca, Jorf Lasfar. Container throughput, trade routes, Africa gateway.', tags: ['port', 'trade', 'Tanger Med', 'Nador', 'Dakhla', 'container', 'TEU', 'shipping', 'infrastructure', 'logistics', 'Africa'], href: '/data/port-strategy' },
  { id: 'carpet-atlas', number: '020', title: 'The Carpet Atlas', category: 'Craft Intelligence', description: 'Regional rug traditions mapped. Beni Ourain, Azilal, Boucherouite, Kilim, Hanbel — origins and motifs.', tags: ['carpet', 'rug', 'beni ourain', 'azilal', 'boucherouite', 'kilim', 'weaving', 'craft', 'atlas mountains'], href: '/data/carpet-atlas' },

  // ═══ 021–030 ═══
  { id: 'musical-traditions', number: '021', title: 'Morocco\'s Musical Traditions', category: 'Cultural Intelligence', description: 'Gnawa, Andalusi, Chaabi, Amazigh, Rai, Malhun, Sufi — eight traditions mapped. Instruments, regions, masters.', tags: ['music', 'gnawa', 'andalusi', 'chaabi', 'amazigh', 'rai', 'malhun', 'sufi', 'guembri', 'oud', 'bendir'], href: '/data/musical-traditions' },
  { id: 'olive-oil-economy', number: '022', title: 'The Olive Oil Economy', category: 'Agricultural Intelligence', description: 'Morocco\'s olive regions, production data, cooperatives, and export markets. Meknes, Fez, Marrakech terroirs.', tags: ['olive', 'oil', 'agriculture', 'meknes', 'cooperatives', 'exports', 'food', 'terroir'], href: '/data/olive-oil-economy' },
  { id: 'imperial-cities', number: '023', title: 'The Four Imperial Cities', category: 'Historical Geography', description: 'Fes, Marrakech, Meknes, Rabat. Each dynasty chose its capital. The power map of Morocco.', tags: ['fes', 'marrakech', 'meknes', 'rabat', 'imperial', 'capital', 'dynasty', 'history'], href: '/data/imperial-cities' },
  { id: 'ramadan-moon', number: '024', title: 'Ramadan Moon', category: 'Living Data', description: 'Hijri calendar, prayer times, ftour traditions, Laylat al-Qadr countdown.', tags: ['ramadan', 'islam', 'prayer', 'fasting', 'ftour', 'mosque', 'calendar', 'hijri', 'moon'], href: '/data/ramadan-moon' },
  { id: 'trans-saharan-trade', number: '025', title: 'Trans-Saharan Trade Routes', category: 'Historical Geography', description: 'Salt, gold, slaves, manuscripts. The ancient trade networks that built Timbuktu and Marrakech.', tags: ['sahara', 'trade', 'gold', 'salt', 'timbuktu', 'caravan', 'desert', 'trans-saharan'], href: '/data/trans-saharan-trade' },
  { id: 'argan-triangle', number: '026', title: 'The Argan Triangle', category: 'Environmental Intelligence', description: 'UNESCO biosphere reserve. The only place on earth argan trees grow. Cooperatives, cosmetics, cooking.', tags: ['argan', 'oil', 'souss', 'essaouira', 'cooperatives', 'women', 'unesco', 'cosmetics', 'tree'], href: '/data/argan-triangle' },
  { id: 'cinema-morocco', number: '027', title: 'Cinema Morocco', category: 'Cultural Intelligence', description: 'Ouarzazate studios, filmed-in-Morocco productions, Game of Thrones locations, Atlas Corporation.', tags: ['cinema', 'film', 'ouarzazate', 'gladiator', 'game of thrones', 'hollywood', 'studio', 'atlas'], href: '/data/cinema-morocco' },
  { id: 'moroccan-tea', number: '028', title: 'The Anatomy of Moroccan Tea', category: 'Food Intelligence', description: 'Chinese gunpowder green tea, fresh mint, sugar. How it arrived, how it\'s made, why it matters.', tags: ['tea', 'mint', 'atay', 'ceremony', 'chinese', 'gunpowder', 'green tea', 'hospitality'], href: '/data/moroccan-tea' },
  { id: 'french-protectorate', number: '029', title: 'The French Protectorate', category: 'Political & Historical Intelligence', description: '1912–1956. Treaty of Fez, Lyautey, villes nouvelles, Rif War, Berber Dahir, Istiqlal, Mohammed V exile, independence.', tags: ['protectorate', 'France', 'Lyautey', 'Prost', 'ville nouvelle', 'colonialism', 'independence', 'Istiqlal', 'Mohammed V', 'Rif', 'Abd el-Krim', 'Treaty of Fez'], href: '/data/french-protectorate' },
  { id: 'hammam-culture', number: '030', title: 'Hammam Culture', category: 'Cultural Intelligence', description: 'The social architecture of the Moroccan bathhouse. Three rooms, six steps, five neighbourhood elements. Design, ritual, products.', tags: ['hammam', 'bathhouse', 'savon beldi', 'black soap', 'kessa', 'ghassoul', 'argan oil', 'ritual', 'ablution', 'mosque', 'medina', 'women', 'culture'], href: '/data/hammam-culture' },

  // ═══ 031–040 ═══
  { id: 'storks-eye-view', number: '031', title: 'A Stork\'s Eye View', category: 'Living Data', description: 'White stork migration, nesting colonies, Gibraltar flyway. Live migration status based on current month.', tags: ['stork', 'bird', 'migration', 'gibraltar', 'nesting', 'chellah', 'volubilis', 'wildlife'], href: '/data/storks-eye-view' },
  { id: 'anatomy-of-a-riad', number: '032', title: 'The Anatomy of a Riad', category: 'Architectural Intelligence', description: 'Courtyard, fountain, zellige, tadelakt, moucharabieh, cedar, gebs. 12 elements, 6 passive climate systems, 0 street-facing windows.', tags: ['riad', 'architecture', 'courtyard', 'zellige', 'tadelakt', 'moucharabieh', 'cedar', 'medina', 'house', 'islamic'], href: '/data/anatomy-of-a-riad' },
  { id: 'cannabis-rif', number: '033', title: 'Cannabis & the Rif', category: 'Economic Intelligence', description: 'The Rif Mountains produce 70% of Europe\'s hashish. 400,000+ people in the trade. Law 13-21 legalization.', tags: ['cannabis', 'rif', 'hashish', 'kif', 'ketama', 'legalization', 'agriculture', 'chefchaouen', 'economy', 'trade'], href: '/data/cannabis-rif' },
  { id: 'atlantic-coast', number: '034', title: 'The Atlantic Coast', category: 'Coastal Intelligence', description: 'Tangier to Dakhla. 3,500 km of coastline, 12 cities mapped. Fishing ports, wind energy, surf breaks, $1.6B Dakhla port.', tags: ['coast', 'atlantic', 'tangier', 'dakhla', 'fishing', 'wind', 'surf', 'port', 'essaouira', 'agadir'], href: '/data/atlantic-coast' },
  { id: 'date-palm-oases', number: '035', title: 'The Date Palm Oases', category: 'Ecological & Agricultural Intelligence', description: 'Draa Valley, Ziz Valley, Tafilalet. Three-tier oasis ecology, 453 cultivars, Bayoud disease, khettara irrigation.', tags: ['date palm', 'oasis', 'Draa', 'Ziz', 'Tafilalet', 'Mejhoul', 'Medjool', 'Bayoud', 'khettara', 'irrigation', 'desert', 'ecology'], href: '/data/date-palm-oases' },
  { id: 'tanneries', number: '036', title: 'The Tanneries', category: 'Craft & Industrial Heritage', description: 'Fez Chouara. 900 years of leather. 1,200 basins, pigeon dung, natural dyes. Process, labour, the 86 that became 3.', tags: ['tannery', 'Chouara', 'Fez', 'Fes', 'leather', 'dye', 'indigo', 'poppy', 'saffron', 'henna', 'babouche', 'craft', 'chromium', 'medina', 'guild'], href: '/data/tanneries' },
  { id: 'jewish-heritage', number: '037', title: 'Jewish Heritage in Morocco', category: 'Cultural & Demographic Intelligence', description: '265,000 in 1948. ~1,000 in 2025. Mellahs, synagogues, cemeteries. Operation Yachin, Cadima, the departure, the preservation.', tags: ['Jewish', 'mellah', 'synagogue', 'Sephardic', 'Operation Yachin', 'Cadima', 'emigration', 'Israel', 'Fez', 'Marrakech', 'Essaouira', 'Mohammed V', 'heritage'], href: '/data/jewish-heritage' },
  { id: 'moroccan-fashion', number: '038', title: 'Moroccan Fashion Intelligence', category: 'Cultural & Design Intelligence', description: 'Caftan, djellaba, babouche, takchita. Six core garments, three embroidery schools. UNESCO 2025. $4.25B textile industry.', tags: ['fashion', 'caftan', 'djellaba', 'babouche', 'takchita', 'sfifa', 'aakad', 'embroidery', 'Fez', 'Rabat', 'UNESCO', 'textile', 'designer', 'artisan', 'wedding'], href: '/data/moroccan-fashion' },
  { id: 'route-thousand-kasbahs', number: '039', title: 'The Route of a Thousand Kasbahs', category: 'Architectural & Geographic Intelligence', description: 'Aït Benhaddou to Skoura. Fortified mud-brick architecture of the Drâa-Tafilalet. 4,000+ earthen settlements. Glaoui dynasty.', tags: ['kasbah', 'ksar', 'Ait Benhaddou', 'Telouet', 'Taourirt', 'Skoura', 'Ouarzazate', 'Glaoui', 'rammed earth', 'pisé', 'UNESCO', 'Draa-Tafilalet', 'Gladiator', 'Game of Thrones'], href: '/data/route-thousand-kasbahs' },
  { id: 'couscous-friday', number: '040', title: 'Couscous Friday', category: 'Culinary & Social Intelligence', description: 'The sacred Friday meal. Seven regional variations, three-steam technique, communal platter. UNESCO 2020.', tags: ['couscous', 'Friday', 'seksu', 'tfaya', 'seffa', 'UNESCO', 'Amazigh', 'communal', 'ritual', 'food', 'semolina', 'Ramadan', 'Maghreb'], href: '/data/couscous-friday' },

  // ═══ 041–050 ═══
  { id: 'weather-portraits', number: '041', title: 'Weather Portraits', category: 'Living Data', description: 'Live weather for 8 Moroccan cities. Open-Meteo integration, NASA satellite imagery toggle.', tags: ['weather', 'temperature', 'climate', 'satellite', 'nasa', 'live', 'marrakech', 'casablanca', 'rain'], href: '/data/weather-portraits' },
  { id: 'automotive-industry', number: '042', title: 'Morocco\'s Automotive Revolution', category: 'Industrial Intelligence', description: 'Renault Tangier, Stellantis Kenitra. How Morocco became Africa\'s #1 car producer.', tags: ['automotive', 'car', 'renault', 'stellantis', 'tangier', 'kenitra', 'industry', 'exports', 'manufacturing'], href: '/data/automotive-industry' },
  { id: 'tagine-atlas', number: '043', title: 'The Tagine Atlas', category: 'Culinary Intelligence', description: 'Regional tagine variations mapped. Marrakech lamb-prune, Fes chicken-olive, coastal fish chermoula, Berber mountain.', tags: ['tagine', 'food', 'cooking', 'lamb', 'chicken', 'fish', 'spice', 'saffron', 'marrakech', 'fes'], href: '/data/tagine-atlas' },
  { id: 'atlas-mountains', number: '044', title: 'The Atlas Mountains', category: 'Physical Geography', description: 'High Atlas, Middle Atlas, Anti-Atlas. Elevation profiles, Toubkal, ski stations, transhumance.', tags: ['atlas', 'mountains', 'toubkal', 'high atlas', 'trekking', 'ski', 'oukaimeden', 'imlil', 'berber'], href: '/data/atlas-mountains' },
  { id: 'bread-of-morocco', number: '045', title: 'The Bread of Morocco', category: 'Food & Agricultural Intelligence', description: 'Khobz, msemen, baghrir, rghaif, harcha. Eight breads. Communal ovens. Wheat dependency — 60%+ imported. The sacred food.', tags: ['bread', 'khobz', 'msemen', 'baghrir', 'rghaif', 'harcha', 'ferran', 'oven', 'communal', 'wheat', 'flour', 'subsidy', 'food security'], href: '/data/bread-of-morocco' },
  { id: 'oldest-universities', number: '046', title: 'The World\'s Oldest Universities', category: 'Educational & Cultural Intelligence', description: 'Al-Qarawiyyin (859 CE). Founded by Fatima al-Fihri. Ben Youssef Madrasa. 229 years before Bologna.', tags: ['Al-Qarawiyyin', 'university', 'oldest', 'Fatima al-Fihri', 'Fez', 'madrasa', 'Ben Youssef', 'Marrakech', 'Bologna', 'Oxford', 'Maimonides', 'Ibn Khaldun', 'UNESCO'], href: '/data/oldest-universities' },
  { id: 'not-all-desert-is-sand', number: '047', title: 'Not All Desert Is Sand', category: 'Geographic & Environmental Intelligence', description: 'Erg, reg, hammada, oued. Four desert types. Only 25% of the Sahara is sand. Erg Chebbi 150m dunes.', tags: ['desert', 'Sahara', 'erg', 'reg', 'hammada', 'oued', 'wadi', 'sand', 'dunes', 'Erg Chebbi', 'Merzouga', 'Erg Chegaga', 'geomorphology', 'arid'], href: '/data/not-all-desert-is-sand' },
  { id: 'surf-coast', number: '048', title: 'Morocco\'s Surf Coast', category: 'Coastal Intelligence', description: '15 surf breaks mapped from Safi to Essaouira. Swell data, season guide, and the economics of a 50,000-guest-per-year surf boom.', tags: ['surf', 'taghazout', 'imsouane', 'anchor point', 'sidi kaouki', 'waves', 'ocean', 'atlantic', 'beach', 'swell'], href: '/data/surf-coast' },
  { id: 'wedding-atlas', number: '049', title: 'The Moroccan Wedding', category: 'Event Intelligence', description: 'Seven days, seven outfits. Henna night, hammam, amariya, negafa, the feast. Regional variations and cost breakdown.', tags: ['wedding', 'marriage', 'henna', 'negafa', 'amariya', 'caftan', 'ceremony', 'tradition', 'family', 'celebration'], href: '/data/wedding-atlas' },
  { id: 'souk-decoded', number: '050', title: 'The Souk Decoded', category: 'Urban Intelligence', description: 'How a Moroccan market is organized. Guilds, pricing logic, negotiation patterns, spatial architecture.', tags: ['souk', 'market', 'medina', 'trade', 'guild', 'craft', 'negotiation', 'commerce', 'economy', 'marrakech'], href: '/data/souk-decoded' },

  // ═══ 051–058 ═══
  { id: 'pottery-traditions', number: '051', title: 'The Pottery Traditions', category: 'Craft Intelligence', description: 'Fes blue, Safi polychrome, Tamegroute green, Rif pottery. Regional ceramics mapped.', tags: ['pottery', 'ceramics', 'fes', 'safi', 'tamegroute', 'craft', 'blue', 'green', 'artisan'], href: '/data/pottery-traditions' },
  { id: 'before-the-sahara', number: '052', title: 'Before the Sahara', category: 'Environmental Intelligence', description: 'Desertification, NDVI vegetation data, oasis collapse, green belt projects. The land between Atlas and sand.', tags: ['desert', 'sahara', 'desertification', 'oasis', 'ndvi', 'vegetation', 'climate', 'drought', 'water', 'green wall'], href: '/data/before-the-sahara' },
  { id: 'harvest-calendar', number: '053', title: 'The Harvest Calendar', category: 'Living Data', description: 'A living clock of Moroccan agriculture. 32 crops, auto-highlights current month, play/pause.', tags: ['harvest', 'agriculture', 'seasonal', 'crops', 'farming', 'calendar', 'live', 'monthly', 'produce'], href: '/data/harvest-calendar' },
  { id: 'bird-atlas', number: '054', title: 'The Bird Atlas', category: 'Wildlife Intelligence', description: 'North Africa\'s bird preservation areas and migration flyways. 27 IBAs, 3 flyways, 509 species.', tags: ['bird', 'migration', 'flyway', 'ibis', 'wildlife', 'nature', 'wetland', 'conservation', 'birdlife'], href: '/data/bird-atlas' },
  { id: 'islamic-spain', number: '055', title: 'Islamic Spain — 781 Years of Al-Andalus', category: 'Historical Timeline', description: 'From Tariq ibn Ziyad\'s 711 crossing to the fall of Granada. Vertical timeline and Mapbox map.', tags: ['al-andalus', 'spain', 'islamic', 'umayyad', 'córdoba', 'granada', 'alhambra', 'reconquista', 'history', '711', '1492', 'caliphate'], href: '/data/islamic-spain' },
  { id: 'gnawa-atlas', number: '056', title: 'The Gnawa Atlas', category: 'Musical & Spiritual Intelligence', description: 'Maalem lineages. Lila ceremony. Guembri construction. Seven spirit colours. Qraqeb. UNESCO 2019. From West African slavery to Morocco\'s most powerful spiritual music.', tags: ['Gnawa', 'Gnaoua', 'maalem', 'guembri', 'sintir', 'qraqeb', 'lila', 'derdeba', 'trance', 'jedba', 'mluk', 'spirits', 'Mahmoud Guinia', 'Essaouira', 'UNESCO', 'Sufi', 'slavery', 'West Africa', 'Pharoah Sanders', 'Randy Weston', 'Hassan Hakmoun', 'Hamid El Kasri', 'blues', 'jazz'], href: '/data/gnawa-atlas' },
  { id: 'gardens-of-morocco', number: '057', title: 'The Gardens of Morocco', category: 'Landscape & Water Intelligence', description: 'Majorelle, Agdal, Menara, Jnan Sbil. Islamic garden design. Khettara water systems. Almohad engineering. 500 hectares of productive paradise. Majorelle Blue #6050DC.', tags: ['garden', 'Majorelle', 'Agdal', 'Menara', 'Jnan Sbil', 'Marrakech', 'Fez', 'Islamic garden', 'chahar bagh', 'khettara', 'qanat', 'seguia', 'noria', 'water', 'irrigation', 'reservoir', 'Almohad', 'Yves Saint Laurent', 'Jacques Majorelle', 'Majorelle Blue', 'UNESCO', 'olive', 'orchard', 'pavilion', 'paradise', 'jannah', 'geometry', 'Berber Museum', 'Pierre Bergé'], href: '/data/gardens-of-morocco' },
  { id: 'migration-routes', number: '058', title: 'Migration Routes Through Morocco', category: 'Human Movement Intelligence', description: 'Sub-Saharan migration corridors. Western Mediterranean and Atlantic routes. Ceuta and Melilla. Transit cities. SNIA policy. 10,457 dead or missing in 2024.', tags: ['migration', 'migrants', 'refugees', 'asylum', 'sub-Saharan', 'Africa', 'Spain', 'Ceuta', 'Melilla', 'Strait of Gibraltar', 'Canary Islands', 'Atlantic route', 'Western Mediterranean', 'Sahara', 'transit', 'Oujda', 'Nador', 'Tangier', 'SNIA', 'regularisation', 'EU', 'Frontex', 'IOM', 'UNHCR', 'Melilla massacre', 'border', 'fence', 'cayucos', 'Mohammed VI', 'deaths', 'Senegal', 'Mali'], href: '/data/migration-routes' },
]
